;;; langs/akkadian.scm — Akkadian / Cuneiform language pack for Curry Scheme.
;;;
;;; This file is the canonical Scheme representation of the Akkadian synonyms
;;; built into the runtime (src/akkadian_names.h).  Loading it is equivalent
;;; to the built-in pack; it exists so the pack can be inspected, forked, or
;;; distributed as a standalone file.
;;;
;;; Usage:
;;;   (import (curry lang))
;;;   (lang:load-file! "langs/akkadian.scm")   ; local
;;;   (lang:install! "akkadian")               ; from registry

(import (curry lang))

(register-language!
  `((id           . "akkadian")
    (display-name . "Akkadian / Cuneiform")
    (intro        . "\xf0\x92\x80\xad Akkadian mode active \xe2\x80\x94 \xc5\xa1ulmu!")
    (error-preamble . "\xf0\x92\x80\xad \xe1\xb8\xabị\xe1\xb9\xadītu \xe2\x80\x94")
    (mappings     .
      ;; (indigenous-name  english-canonical  "optional cultural note")
       (šakānum define)
       (𒁹 define)
       (epēšum lambda)
       (𒇽 lambda)
       (šumma if "phonetic ŠU.MA")
       (𒋗𒈠 if "phonetic ŠU.MA")
       (ištartu begin)
       (𒀸 begin)
       (šanûm set! "BA.A = to change")
       (𒁀𒀀 set! "BA.A = to change")
       (leqûm let)
       (𒅁 let)
       (leqûm-watrum let* "IB.U = sequential")
       (𒅁𒌋 let* "IB.U = sequential")
       (leqûm-tadārum letrec "IB.GI = mutual")
       (𒅁𒄀 letrec "IB.GI = mutual")
       (leqûm-tadārum-w letrec*)
       (𒅁𒄀𒌋 letrec*)
       (kīma quote "KI.MA = as-it-is")
       (𒆠𒈠 quote "KI.MA = as-it-is")
       (kīma-libbi quasiquote)
       (𒆠𒈠𒅁 quasiquote)
       (pašārum unquote "NU.KI = un-place")
       (𒉡𒆠 unquote "NU.KI = un-place")
       (pašārum-šapārum unquote-splicing)
       (𒉡𒆠𒊕 unquote-splicing)
       (u and "U = the conjunction!")
       (𒌋 and "U = the conjunction!")
       (lū or "LU")
       (𒇻 or "LU")
       (šumma-ribûm cond "ŠU = hand/choice")
       (𒋗 cond "ŠU = hand/choice")
       (ana case "A.NA = for/to")
       (𒀀𒈾 case "A.NA = for/to")
       (inūma when "UD = time/when!")
       (𒌑 when "UD = time/when!")
       (lā-inūma unless "NU.UD = not-when")
       (𒉡𒌑 unless "NU.UD = not-when")
       (alākum do "I = to go")
       (𒄿 do "I = to go")
       (šakānum-ṭupšarrim define-syntax "DIŠ.UM")
       (𒁹𒌝 define-syntax "DIŠ.UM")
       (ṭupšarrūtum syntax-rules "UM.U")
       (𒌝𒌋 syntax-rules "UM.U")
       (šakānum-nikkassī define-values "DIŠ.ME")
       (𒁹𒈷 define-values "DIŠ.ME")
       (šakānum-ṣimtim define-record-type "DIŠ.TAR")
       (𒁹𒋻 define-record-type "DIŠ.TAR")
       (nikkassū values "ME = essence/values")
       (𒈷 values "ME = essence/values")
       (riksum call/cc "LAL.DIŠ = binding")
       (𒇲𒁹 call/cc "LAL.DIŠ = binding")
       (riksum-dannum call-with-current-continuation)
       (𒇲𒁹𒃲 call-with-current-continuation)
       (erēbum import "EN = lord/enter")
       (𒂗 import "EN = lord/enter")
       (waṣûm export "EN.NU = exit")
       (𒂗𒉡 export "EN.NU = exit")
       (bīt-ṭuppi define-library "E2.UM = house of tablets!")
       (𒂍𒌝 define-library "E2.UM = house of tablets!")
       (naṣārum guard "KI.EN = ground-lord")
       (𒆠𒂗 guard "KI.EN = ground-lord")
       (šīmtum parameterize)
       (𒁹𒆠 parameterize)
       (qebûm include)
       (𒁀𒌝 include)
       (naṭālum-arkûm delay "UD.AŠ2 = time-first")
       (𒌑𒀸 delay "UD.AŠ2 = time-first")
       (wālādum spawn "IB.A = to beget")
       (𒅁𒀀 spawn "IB.A = to beget")
       (šapārum send! "UM = tablet = letter!")
       (𒌝 send! "UM = tablet = letter!")
       (maḫārum receive "MA.ḪI = to receive")
       (𒈠𒄭 receive "MA.ḪI = to receive")
       (rakāsum cons "LAL = to bind")
       (𒇲 cons "LAL = to bind")
       (rēšum car "SAG = head!")
       (𒊕 car "SAG = head!")
       (zibbatum cdr "KUN = tail!")
       (𒆜 cdr "KUN = tail!")
       (nindabûm list "I.UM = proceeding tablets")
       (𒄿𒌝 list "I.UM = proceeding tablets")
       (mīnum length "MA.NA = mana (weight/measure)")
       (𒈠𒈾 length "MA.NA = mana (weight/measure)")
       (redûm append "MA.EN = follow-on")
       (𒈠𒂗 append "MA.EN = follow-on")
       (turrum reverse "TAR.A = to turn")
       (𒋻𒀀 reverse "TAR.A = to turn")
       (nindabûm-maḫārum list-ref)
       (𒌝𒊕 list-ref)
       (nindabûm-zibbat list-tail)
       (𒌝𒆜 list-tail)
       (šutakūlum-nindabî map "ME.IGI = see-essence = map")
       (𒈷𒅆 map "ME.IGI = see-essence = map")
       (ana-kālāma for-each "A.NA.KI = for-all")
       (𒀀𒈾𒆠 for-each "A.NA.KI = for-all")
       (ṣêrum filter "TAR = to cut/select")
       (𒋻 filter "TAR = to cut/select")
       (lapātum-šumēlam fold-left)
       (𒇲𒆠 fold-left)
       (lapātum-imittam fold-right)
       (𒇲𒌋 fold-right)
       (ṭuppum-maḫārum assoc "UM.MA.DIŠ")
       (𒌝𒈠𒁹 assoc "UM.MA.DIŠ")
       (ṭuppum-maḫārum-eq assq "UM.EN.DIŠ")
       (𒌝𒂗𒁹 assq "UM.EN.DIŠ")
       (libbum-maḫārum member)
       (𒌝𒊕𒊕 member)
       (šūnum? null? "NU.DIŠ = not-one = empty")
       (𒉡𒁹 null? "NU.DIŠ = not-one = empty")
       (qitnūm? pair? "LAL.LAL = bound pair")
       (𒇲𒇲 pair? "LAL.LAL = bound pair")
       (nindabûm? list? "---- Procedures: arithmetic ----")
       (𒌝𒌝 list? "---- Procedures: arithmetic ----")
       (matāḫum + "TAR.DIŠ — addition")
       (𒋻𒁹 + "TAR.DIŠ — addition")
       (ḫarāṣum - "LAL.UD — to reduce/cut")
       (𒇲𒌑 - "LAL.UD — to reduce/cut")
       (šutakūlum * "MAŠ.DIŠ — multiplication (Babylonian term!)")
       (𒈧𒁹 * "MAŠ.DIŠ — multiplication (Babylonian term!)")
       (zâzum / "MAŠ — to halve/divide (Babylonian term!)")
       (𒈧 / "MAŠ — to halve/divide (Babylonian term!)")
       (mitḫārum = "MA.TAR — equal (Babylonian math term!)")
       (𒈠𒋻 = "MA.TAR — equal (Babylonian math term!)")
       (ṣeḫērum < "NU.GAL = not-great = lesser")
       (𒉡𒃲 < "NU.GAL = not-great = lesser")
       (rabûm > "GAL = great!")
       (𒃲 > "GAL = great!")
       (ṣeḫērum-mitḫārum <= "not-great-or-equal")
       (𒉡𒃲𒁹 <= "not-great-or-equal")
       (rabûm-mitḫārum >=)
       (𒃲𒁹 >=)
       (ašarēdum max "GAL.GAL = greatest")
       (𒃲𒃲 max "GAL.GAL = greatest")
       (ṣiḫrum min "NU.NU = smallest")
       (𒉡𒉡 min "NU.NU = smallest")
       (kīttum abs "KI.AŠ2 = truth-one")
       (𒆠𒀸 abs "KI.AŠ2 = truth-one")
       (ṣifrum? zero? "zero = ṣifrum, whence \"cipher\"")
       (𒉡𒉡𒁹 zero? "zero = ṣifrum, whence \"cipher\"")
       (damqum? positive? "GAL.UD = great-day = positive")
       (𒃲𒌑 positive? "GAL.UD = great-day = positive")
       (lemnûm? negative? "NU.I = not-going = negative")
       (𒉡𒄿 negative? "NU.I = not-going = negative")
       (zûzum? odd?)
       (𒀸𒁹 odd?)
       (šinûm? even?)
       (𒀸𒀸 even?)
       (šaplûm floor "KI = ground/earth = floor!")
       (𒆠 floor "KI = ground/earth = floor!")
       (elûm ceiling "AN.AŠ2 = sky-one = ceiling")
       (𒀭𒀸 ceiling "AN.AŠ2 = sky-one = ceiling")
       (labārum round)
       (𒄀𒁹 round)
       (ḫarāṣum-warkûm truncate "TAR.LAL = cut-bind")
       (𒋻𒇲 truncate "TAR.LAL = cut-bind")
       (napḫarum expt "ME.ME = power")
       (𒈷𒈷 expt "ME.ME = power")
       (ibum sqrt "IB.DIŠ — ibum = \"the side\" = square root in Babylonian math!")
       (𒅁𒁹 sqrt "IB.DIŠ — ibum = \"the side\" = square root in Babylonian math!")
       (qātum quotient)
       (𒁀𒁹 quotient)
       (šērum remainder)
       (𒊕𒌝 remainder)
       (kippatum modulo)
       (𒄀𒌋 modulo)
       (kabrum gcd)
       (𒃲𒁹𒁹 gcd)
       (qallum lcm "NU.GAL.UD = least common")
       (𒉡𒃲𒌑 lcm "NU.GAL.UD = least common")
       (mitḫartum square "MA.TAR.DIŠ = equal-cut-one = x²")
       (𒈠𒋻𒁹 square "MA.TAR.DIŠ = equal-cut-one = x²")
       (kinattu-nikkassum? exact-integer? "KI.AŠ2? = earth-first = whole & exact?")
       (𒆠𒀸? exact-integer? "KI.AŠ2? = earth-first = whole & exact?")
       (qātum-ḫarāṣim truncate-quotient "BA.TAR.DIŠ = give-cut-one")
       (𒁀𒋻𒁹 truncate-quotient "BA.TAR.DIŠ = give-cut-one")
       (šērum-ḫarāṣim truncate-remainder "SAG.TAR = head-cut")
       (𒊕𒋻 truncate-remainder "SAG.TAR = head-cut")
       (ḫarāṣum-kala truncate/ "TAR.ME.ME = cut-both = both results")
       (𒋻𒈷𒈷 truncate/ "TAR.ME.ME = cut-both = both results")
       (ibum-kinattu exact-integer-sqrt "IB.KI.DIŠ = exact root (ibum = \"the side\" = OB square root)")
       (𒅁𒆠𒁹 exact-integer-sqrt "IB.KI.DIŠ = exact root (ibum = \"the side\" = OB square root)")
       (kinattu exact)
       (𒆠𒋻 exact)
       (lā-kinattu inexact)
       (𒉡𒆠𒋻 inexact)
       (nikkassum-ana-ṭuppi number->string)
       (𒈷𒌝 number->string)
       (ṭuppum-ana-nikkassim string->number "Transcendental")
       (𒌝𒈷 string->number "Transcendental")
       (šapaltu-ṣīrum sin)
       (𒁹𒀸𒁹 sin)
       (ašarēdum-ṣīrum cos)
       (𒁹𒁹𒀸 cos)
       (napḫarum-ṣīrum exp)
       (𒈷𒁹𒀸 exp)
       (naṭālum-ṣīrum log)
       (𒅆𒁹 log)
       (šapaltu-ippeš atan "---- Procedures: type predicates ----")
       (𒁹𒀸𒀸 atan "---- Procedures: type predicates ----")
       (nikkassum? number? "ME? = is essence?")
       (𒈷? number? "ME? = is essence?")
       (ṭupšarrum? string? "UM? = is tablet?")
       (𒌝? string? "UM? = is tablet?")
       (šumum? symbol?)
       (𒁹𒌝? symbol?)
       (kēnum? boolean?)
       (𒆠𒀸? boolean?)
       (pārisum? procedure? "LU2? = is person/agent?")
       (𒇽? procedure? "LU2? = is person/agent?")
       (nindabûm-šupur? vector?)
       (𒌝𒀸? vector?)
       (ṣibtum? char?)
       (𒁹? char?)
       (bābum? port? "E2? = is gate?")
       (𒂍? port? "E2? = is gate?")
       (kinattu? exact?)
       (𒆠? exact?)
       (lā-kinattu? inexact?)
       (𒉡𒆠? inexact?)
       (nikkassum-šalim? integer?)
       (𒈷𒀸? integer?)
       (ḫepûm? rational?)
       (𒈷𒁹? rational?)
       (ṣīrum? real?)
       (𒈷𒀀? real?)
       (išārum? complex?)
       (𒈷𒌝? complex?)
       (mitḫārum-eq? eq? "EN.EN? = same lord?")
       (𒂗𒂗? eq? "EN.EN? = same lord?")
       (mitḫārum-eqv? eqv?)
       (𒈠𒈠? eqv?)
       (mitḫārum-šalim? equal? "---- Procedures: I/O ----")
       (𒈠𒋻? equal? "---- Procedures: I/O ----")
       (naṭālum display "IGI = eye/to look!")
       (𒅆 display "IGI = eye/to look!")
       (šaṭārum write "UM.DIŠ = write-mark")
       (𒌝𒁹 write "UM.DIŠ = write-mark")
       (pirištu newline "DIŠ.DIŠ.DIŠ = new line mark")
       (𒁹𒁹𒁹 newline "DIŠ.DIŠ.DIŠ = new line mark")
       (šemûm read "IGI.AŠ2 = to look-read")
       (𒅆𒀸 read "IGI.AŠ2 = to look-read")
       (šemûm-ašrum read-line)
       (𒅆𒌋 read-line)
       (šemûm-ṣibtum read-char "IGI.BA = see-give = read one")
       (𒅆𒁀 read-char "IGI.BA = see-give = read one")
       (šaṭārum-ṣibtum write-char)
       (𒌝𒅆 write-char)
       (šaṭārum-ṭuppam write-string "IGI.UM = see-tablet")
       (𒅆𒌝 write-string "IGI.UM = see-tablet")
       (petûm-ṭuppi-erēbim open-input-file)
       (𒂍𒂗 open-input-file)
       (petûm-ṭuppi-waṣîm open-output-file)
       (𒂍𒉡 open-output-file)
       (sakārum close-port "E2.LAL = bind the house")
       (𒂍𒇲 close-port "E2.LAL = bind the house")
       (pašārum-bābim flush-output-port)
       (𒂍𒁀 flush-output-port)
       (qātum? eof-object? "NU.UM = no more tablet")
       (𒉡𒌝? eof-object? "NU.UM = no more tablet")
       (ṣibtum-maḫrum? char-ready? "IGI.BA? = seen-ready?")
       (𒅆𒁀? char-ready? "IGI.BA? = seen-ready?")
       (ṣibtum-riqqi-maḫrum? u8-ready? "IGI.DIŠ? = raw-byte ready?")
       (𒅆𒁹? u8-ready? "IGI.DIŠ? = raw-byte ready?")
       (šemûm-ṣibtum-riqqi read-u8 "IGI.BA.DIŠ = read one raw byte")
       (𒅆𒁀𒁹 read-u8 "IGI.BA.DIŠ = read one raw byte")
       (naṭālum-ṣibtum-riqqi peek-u8 "IGI.NU.DIŠ = look-not-one = peek without consuming")
       (𒅆𒉡𒁹 peek-u8 "IGI.NU.DIŠ = look-not-one = peek without consuming")
       (šemûm-ṭuppam read-string "IGI.UM = read tablet")
       (𒅆𒌝 read-string "IGI.UM = read tablet")
       (šemûm-ṭuppi-ṣibtātim read-bytevector "IGI.UM.BA = read byte-tablet")
       (𒅆𒌝𒁀 read-bytevector "IGI.UM.BA = read byte-tablet")
       (šemûm-ṭuppi-ṣibtātim-ina read-bytevector! "IGI.UM.BA.DIŠ = read into existing")
       (𒅆𒌝𒁀𒁹 read-bytevector! "IGI.UM.BA.DIŠ = read into existing")
       (šaṭārum-ṣibtum-riqqi write-u8 "UM.BA.DIŠ = write one raw byte")
       (𒌝𒁀𒁹 write-u8 "UM.BA.DIŠ = write one raw byte")
       (šaṭārum-ṭuppi-ṣibtātim write-bytevector "UM.BA = write byte-tablet")
       (𒌝𒁀 write-bytevector "UM.BA = write byte-tablet")
       (šaṭārum-ṣīrum write-simple "UM.I = write-going = simple/non-recursive write")
       (𒌝𒄿 write-simple "UM.I = write-going = simple/non-recursive write")
       (ṭuppum-ibašši? file-exists? "E2.AŠ2? = does the tablet-house exist?")
       (𒂍𒀸? file-exists? "E2.AŠ2? = does the tablet-house exist?")
       (ḫepûm-ṭuppi delete-file "TAR.E2 = cut-house = destroy the tablet")
       (𒋻𒂍 delete-file "TAR.E2 = cut-house = destroy the tablet")
       (šemûm-ina-ṭuppi call-with-input-file "E2.IGI = file-read")
       (𒂍𒅆 call-with-input-file "E2.IGI = file-read")
       (šaṭārum-ina-ṭuppi call-with-output-file "E2.UM = file-write")
       (𒂍𒌝 call-with-output-file "E2.UM = file-write")
       (ina-ṭuppi-šemûm with-input-from-file "E2.IGI.DIŠ = from-file-read-one")
       (𒂍𒅆𒁹 with-input-from-file "E2.IGI.DIŠ = from-file-read-one")
       (ana-ṭuppi-šaṭārum with-output-to-file "E2.UM.DIŠ = to-file-write-one")
       (𒂍𒌝𒁹 with-output-to-file "E2.UM.DIŠ = to-file-write-one")
       (epēšum-ṭuppam make-string)
       (𒇽𒌝 make-string)
       (ṭuppum string "UD.UM = day-tablet")
       (𒌑𒌝 string "UD.UM = day-tablet")
       (mīnum-ṭuppim string-length)
       (𒈠𒌝 string-length)
       (maḫārum-ṭuppim string-ref "UD.SAG = time-head")
       (𒌑𒊕 string-ref "UD.SAG = time-head")
       (redûm-ṭuppim string-append "UM.I = tablet-going")
       (𒌝𒄿 string-append "UM.I = tablet-going")
       (šutur-ṭuppim string-copy)
       (𒌝𒁹𒁹 string-copy)
       (libbum-ṭuppim substring)
       (𒌝𒅁 substring)
       (ṭuppum-ana-nindabî string->list)
       (𒌝𒇽 string->list)
       (nindabûm-ana-ṭuppi list->string "LU2.LU2.UM = many-to-tablet")
       (𒇽𒇽𒌝 list->string "LU2.LU2.UM = many-to-tablet")
       (elûm-ṭuppim string-upcase)
       (𒌝𒃲 string-upcase)
       (šaplûm-ṭuppim string-downcase)
       (𒌝𒆠 string-downcase)
       (mitḫārum-ṭuppim? string=?)
       (𒌝𒈠? string=?)
       (ṣeḫērum-ṭuppim? string<?)
       (𒌝𒉡? string<?)
       (ṭuppum-ana-šumim string->symbol "UM.AŠ2 = tablet-to-one")
       (𒌝𒀸 string->symbol "UM.AŠ2 = tablet-to-one")
       (šumum-ana-ṭuppi symbol->string "U.SAG = ten-head = name")
       (𒌋𒊕 symbol->string "U.SAG = ten-head = name")
       (ṣeḫērum-mitḫārum-ṭuppim? string<=? "UM.NU.DIŠ? = not-great-one-tablet?")
       (𒌝𒉡𒁹? string<=? "UM.NU.DIŠ? = not-great-one-tablet?")
       (rabûm-ṭuppim? string>? "UM.GAL? = great-tablet?")
       (𒌝𒃲? string>? "UM.GAL? = great-tablet?")
       (rabûm-mitḫārum-ṭuppim? string>=? "UM.GAL.DIŠ? = great-one-tablet?")
       (𒌝𒃲𒁹? string>=? "UM.GAL.DIŠ? = great-one-tablet?")
       (mithāriš-mitḫārum-ṭuppim? string-ci=? "MA.UM.MA? = same-tablet-equal?")
       (𒈠𒌝𒈠? string-ci=? "MA.UM.MA? = same-tablet-equal?")
       (mithāriš-ṣeḫērum-ṭuppim? string-ci<? "MA.UM.NU?")
       (𒈠𒌝𒉡? string-ci<? "MA.UM.NU?")
       (mithāriš-rabûm-ṭuppim? string-ci>? "MA.UM.GAL?")
       (𒈠𒌝𒃲? string-ci>? "MA.UM.GAL?")
       (mithāriš-ṣeḫērum-mitḫārum-ṭuppim? string-ci<=? "MA.UM.NU.DIŠ?")
       (𒈠𒌝𒉡𒁹? string-ci<=? "MA.UM.NU.DIŠ?")
       (mithāriš-rabûm-mitḫārum-ṭuppim? string-ci>=? "MA.UM.GAL.DIŠ?")
       (𒈠𒌝𒃲𒁹? string-ci>=? "MA.UM.GAL.DIŠ?")
       (šakānum-ṭuppim string-set! "UM.TAR = tablet-set")
       (𒌝𒋻 string-set! "UM.TAR = tablet-set")
       (katābum-ṭuppim string-copy! "UM.UD.TAR = overwrite tablet")
       (𒌝𒌑𒋻 string-copy! "UM.UD.TAR = overwrite tablet")
       (ana-kālāma-ṭuppim string-for-each "A.UM = for-tablet")
       (𒀀𒌝 string-for-each "A.UM = for-tablet")
       (malûm-ṭuppim string-fill! "UM.U.DIŠ = fill-tablet-one (malûm = to fill)")
       (𒌝𒌋𒁹 string-fill! "UM.U.DIŠ = fill-tablet-one (malûm = to fill)")
       (ṭuppum-mithāriš string-foldcase "UD.UM = time-tablet = folded tablet")
       (𒌑𒌝 string-foldcase "UD.UM = time-tablet = folded tablet")
       (ṭuppum-ana-ṣibtātim string->utf8 "UM.BA = tablet-to-bytes")
       (𒌝𒁀 string->utf8 "UM.BA = tablet-to-bytes")
       (ṣibtātum-ana-ṭuppi utf8->string "BA.UM = bytes-to-tablet")
       (𒁀𒌝 utf8->string "BA.UM = bytes-to-tablet")
       (epēšum-ṣindum make-vector)
       (𒇽𒀸 make-vector)
       (ṣindānum vector)
       (𒀸𒌋 vector)
       (mīnum-ṣindim vector-length)
       (𒈠𒀸 vector-length)
       (maḫārum-ṣindim vector-ref)
       (𒀸𒊕 vector-ref)
       (šakānum-ṣindim vector-set! "AŠ2.TAR = one-cut = set")
       (𒀸𒋻 vector-set! "AŠ2.TAR = one-cut = set")
       (ṣindānum-ana-nindabî vector->list)
       (𒀸𒇽 vector->list)
       (nindabûm-ana-ṣindim list->vector "LU2.LU2.AŠ2 = many-to-one")
       (𒇽𒇽𒀸 list->vector "LU2.LU2.AŠ2 = many-to-one")
       (malûm-ṣindim vector-fill!)
       (𒀸𒌋𒁹 vector-fill!)
       (šutur-ṣindim vector-copy)
       (𒀸𒁹𒁹 vector-copy)
       (šutakūlum-ṣindim vector-map)
       (𒈧𒀸 vector-map)
       (ana-kālāma-ṣindim vector-for-each)
       (𒀀𒀸 vector-for-each)
       (redûm-ṣindim vector-append "AŠ2.I = one-going = vector-continuing")
       (𒀸𒄿 vector-append "AŠ2.I = one-going = vector-continuing")
       (šutur-ṣindim-ina vector-copy! "AŠ2.I.DIŠ = one-going-into = copy into")
       (𒀸𒄿𒁹 vector-copy! "AŠ2.I.DIŠ = one-going-into = copy into")
       (epēšum-ṭuppi-ṣibtātim make-bytevector "LU2.UM.BA = make byte-tablet")
       (𒇽𒌝𒁀 make-bytevector "LU2.UM.BA = make byte-tablet")
       (ṭuppum-ṣibtātim bytevector "UD.UM.BA = the byte-tablet (constructor)")
       (𒌑𒌝𒁀 bytevector "UD.UM.BA = the byte-tablet (constructor)")
       (mīnum-ṭuppi-ṣibtātim bytevector-length "MA.UM.BA = count of the byte-tablet")
       (𒈠𒌝𒁀 bytevector-length "MA.UM.BA = count of the byte-tablet")
       (maḫārum-ṭuppi-ṣibtātim bytevector-u8-ref "UM.BA.SAG = byte-tablet head/index")
       (𒌝𒁀𒊕 bytevector-u8-ref "UM.BA.SAG = byte-tablet head/index")
       (šakānum-ṭuppi-ṣibtātim bytevector-u8-set! "UM.BA.TAR = set in byte-tablet")
       (𒌝𒁀𒋻 bytevector-u8-set! "UM.BA.TAR = set in byte-tablet")
       (šutur-ṭuppi-ṣibtātim bytevector-copy "UM.BA.DIŠ.DIŠ = copy byte-tablet")
       (𒌝𒁀𒁹𒁹 bytevector-copy "UM.BA.DIŠ.DIŠ = copy byte-tablet")
       (šutur-ṭuppi-ṣibtātim-ina bytevector-copy! "UM.BA.I.DIŠ = copy-into byte-tablet")
       (𒌝𒁀𒄿𒁹 bytevector-copy! "UM.BA.I.DIŠ = copy-into byte-tablet")
       (redûm-ṭuppi-ṣibtātim bytevector-append "UM.BA.I = byte-tablet-continuing")
       (𒌝𒁀𒄿 bytevector-append "UM.BA.I = byte-tablet-continuing")
       (ṣibtum-ana-nikkassim char->integer "BA.ME = give essence")
       (𒁀𒈷 char->integer "BA.ME = give essence")
       (nikkassum-ana-ṣibtim integer->char "Character comparators — ṣibtum (the sign/character) + comparator")
       (𒈷𒁹 integer->char "Character comparators — ṣibtum (the sign/character) + comparator")
       (mitḫārum-ṣibtim? char=? "BA.MA? = sign-equal?")
       (𒁀𒈠? char=? "BA.MA? = sign-equal?")
       (ṣeḫērum-ṣibtim? char<? "BA.NU.GAL? = sign-not-great?")
       (𒁀𒉡𒃲? char<? "BA.NU.GAL? = sign-not-great?")
       (ṣeḫērum-ū-mitḫārum-ṣibtim? char<=? "BA.NU.GAL.DIŠ?")
       (𒁀𒉡𒃲𒁹? char<=? "BA.NU.GAL.DIŠ?")
       (rabûm-ṣibtim? char>? "BA.GAL? = sign-great?")
       (𒁀𒃲? char>? "BA.GAL? = sign-great?")
       (rabûm-ū-mitḫārum-ṣibtim? char>=? "BA.GAL.DIŠ?")
       (𒁀𒃲𒁹? char>=? "BA.GAL.DIŠ?")
       (mithāriš-mitḫārum-ṣibtim? char-ci=? "BA.MA.MA? = sign-uniform-equal?")
       (𒁀𒈠𒈠? char-ci=? "BA.MA.MA? = sign-uniform-equal?")
       (mithāriš-ṣeḫērum-ṣibtim? char-ci<? "BA.MA.NU.GAL?")
       (𒁀𒈠𒉡𒃲? char-ci<? "BA.MA.NU.GAL?")
       (mithāriš-rabûm-ṣibtim? char-ci>? "BA.MA.GAL?")
       (𒁀𒈠𒃲? char-ci>? "BA.MA.GAL?")
       (mithāriš-ṣeḫērum-mitḫārum-ṣibtim? char-ci<=? "BA.MA.NU.GAL.DIŠ?")
       (𒁀𒈠𒉡𒃲𒁹? char-ci<=? "BA.MA.NU.GAL.DIŠ?")
       (mithāriš-rabûm-mitḫārum-ṣibtim? char-ci>=? "BA.MA.GAL.DIŠ?")
       (𒁀𒈠𒃲𒁹? char-ci>=? "BA.MA.GAL.DIŠ?")
       (nikkassum-ša-ṣibtim digit-value "ME.BA = essence of the sign")
       (𒈷𒁀 digit-value "ME.BA = essence of the sign")
       (ṣibtum-mithāriš char-foldcase "BA.MA = sign-uniform")
       (𒁀𒈠 char-foldcase "BA.MA = sign-uniform")
       (lā not "NU = negation!")
       (𒉡 not "NU = negation!")
       (mitḫārum-kēnim? boolean=? "---- Procedures: math utilities ----")
       (𒆠𒆠? boolean=? "---- Procedures: math utilities ----")
       (paqādum apply "LU2.I = person-goes")
       (𒇽𒄿 apply "LU2.I = person-goes")
       (ḫiṭītum error "same root as akkadian.h")
       (𒄷𒁹 error "same root as akkadian.h")
       (našûm raise "---- Procedures: actors ----")
       (𒃲𒁹𒌋 raise "---- Procedures: actors ----")
       (wālādum spawn)
       (𒅁𒀀 spawn)
       (šapārum send! "UM.EN = send tablet")
       (𒌝𒂗 send! "UM.EN = send tablet")
       (maḫārum receive "UM.MA = receive tablet")
       (𒌝𒈠 receive "UM.MA = receive tablet")
       (ramānī self "ZA = self/stone")
       (𒍪 self "ZA = self/stone")
       (balāṭum? actor-alive? "---- Procedures: macros ----")
       (𒅁𒃲? actor-alive? "---- Procedures: macros ----")
       (ṭupšarrūtum ṣibātum syntax-rules "UM.TAR — template-pattern")
       (𒌝𒋻 syntax-rules "UM.TAR — template-pattern")
       (la-idûm sym-var "NU.IGI = not-seen = the unknown")
       (𒉡𒅆 sym-var "NU.IGI = not-seen = the unknown")
       (la-idûm? sym-var?)
       (𒉡𒅆? sym-var?)
       (awât-la-idûm? sym-expr? "NU.UM? = not-tablet? = unsettled")
       (𒉡𒌝? sym-expr? "NU.UM? = not-tablet? = unsettled")
       (la-idûm-šalim? symbolic? "NU.IGI.DIŠ? = unknown-or-expression")
       (𒉡𒅆𒁹? symbolic? "NU.IGI.DIŠ? = unknown-or-expression")
       (šum-la-idûm sym-var-name "NU.SAG = not-seen-head = its name")
       (𒉡𒊕 sym-var-name "NU.SAG = not-seen-head = its name")
       (ṣimdat-la-idûm? sym-assumption? "TAR.NU.IGI? = is this the decree of the unknown?")
       (𒋻𒉡𒅆? sym-assumption? "TAR.NU.IGI? = is this the decree of the unknown?")
       (māḫirum sym-diff "ḪI.SAG = rate-head")
       (𒄭𒊕 sym-diff "ḪI.SAG = rate-head")
       (māḫirum-ḫepûm frac-diff "ḪI.MA  = halved-rate")
       (𒄭𒈠 frac-diff "ḪI.MA  = halved-rate")
       (māḫirum-išārum wirtinger-d "ḪI.DIŠ = rate-one  (holomorphic ∂/∂z)")
       (𒄭𒁹 wirtinger-d "ḪI.DIŠ = rate-one  (holomorphic ∂/∂z)")
       (māḫirum-la wirtinger-dbar "ḪI.NU  = rate-not  (anti-holomorphic ∂/∂z̄)")
       (𒄭𒉡 wirtinger-dbar "ḪI.NU  = rate-not  (anti-holomorphic ∂/∂z̄)")
       (māḫirum-ramāni auto-diff "ḪI.ZA  = rate-self (forward-mode via dual)")
       (𒄭𒍪 auto-diff "ḪI.ZA  = rate-self (forward-mode via dual)")
       (eqlum integrate "AN.KI = sky-earth = the bounded field")
       (𒀭𒆠 integrate "AN.KI = sky-earth = the bounded field")
       (eqlum-ḫepûm frac-int "AN.KI.MA = halved-field")
       (𒀭𒆠𒈠 frac-int "AN.KI.MA = halved-field")
       (šuklulum simplify "DIŠ.KI.DIŠ = one-earth-one")
       (𒁹𒆠𒁹 simplify "DIŠ.KI.DIŠ = one-earth-one")
       (nukkurum substitute "BA.TAR = give-cut = exchange")
       (𒁀𒋻 substitute "BA.TAR = give-cut = exchange")
       (rapāšum expand "GAL.A = greatly-spread")
       (𒃲𒀀 expand "GAL.A = greatly-spread")
       (elûm-ṣīrum degree "AN.ME = sky-essence = the highest")
       (𒀭𒈷 degree "AN.ME = sky-essence = the highest")
       (kânum collect "KI.DIŠ.DIŠ = earth-gathered")
       (𒆠𒁹𒁹 collect "KI.DIŠ.DIŠ = earth-gathered")
       (rēšum-nikkassī leading-coeff "SAG.ME = head-essence")
       (𒊕𒈷 leading-coeff "SAG.ME = head-essence")
       (tawirtum conjugate "IGI.TAR = eye-cut = reflected")
       (𒅆𒋻 conjugate "IGI.TAR = eye-cut = reflected")
       (tawirtum-ṣīrum conj "IGI.TAR.DIŠ = short conjugate")
       (𒅆𒋻𒁹 conj "IGI.TAR.DIŠ = short conjugate")
       (ṭuppi-la-idûm sym->string "NU.IGI.UM")
       (𒉡𒅆𒌝 sym->string "NU.IGI.UM")
       (ṭuppi-la-idûm-išārum sym->infix "NU.IGI.UM.U = infix tablet")
       (𒉡𒅆𒌝𒌋 sym->infix "NU.IGI.UM.U = infix tablet")
       (ṭuppi-ṣīrum-la-idûm sym->latex "NU.IGI.UM.DIŠ = formal tablet")
       (𒉡𒅆𒌝𒁹 sym->latex "NU.IGI.UM.DIŠ = formal tablet")
       (ša-dāriš? surreal? "AN.DIŠ?   = is it eternal?")
       (𒀭𒁹? surreal? "AN.DIŠ?   = is it eternal?")
       (dāriš? surreal-infinite? "AN.AN?    = doubly eternal?")
       (𒀭𒀭? surreal-infinite? "AN.AN?    = doubly eternal?")
       (la-dāriš? surreal-finite? "NU.AN?    = not eternal")
       (𒉡𒀭? surreal-finite? "NU.AN?    = not eternal")
       (ṣiḫrum-ṣīrum? surreal-infinitesimal? "NU.NU.A?  = supremely tiny?")
       (𒉡𒉡𒀀? surreal-infinitesimal? "NU.NU.A?  = supremely tiny?")
       (ṣīrum-ša-dāriš surreal-real-part "AN.I      = the standard going part")
       (𒀭𒄿 surreal-real-part "AN.I      = the standard going part")
       (ša-dāriš-kīnum surreal-omega-part "AN.AN.DIŠ = the ω-coefficient")
       (𒀭𒀭𒁹 surreal-omega-part "AN.AN.DIŠ = the ω-coefficient")
       (ša-ṣiḫrim surreal-epsilon-part "NU.NU.ME  = the ε-essence")
       (𒉡𒉡𒈷 surreal-epsilon-part "NU.NU.ME  = the ε-essence")
       (ūm-wulludim surreal-birthday "UD.IB     = day-hold = birth-day")
       (𒌑𒅁 surreal-birthday "UD.IB     = day-hold = birth-day")
       (mīnum-ša-dāriš surreal-nterms "AN.MA     = count of the eternal")
       (𒀭𒈠 surreal-nterms "AN.MA     = count of the eternal")
       (ša-dāriš-ana-nikkassim surreal->number "AN.UD     = eternal to temporal")
       (𒀭𒌑 surreal->number "AN.UD     = eternal to temporal")
       (epēšum-ša-dāriš make-surreal "AN.LU2   = make the eternal")
       (𒀭𒇽 make-surreal "AN.LU2   = make the eternal")
       (nindabûm-ša-dāriš surreal-terms "AN.UM    = the eternal's tablets")
       (𒀭𒌝 surreal-terms "AN.UM    = the eternal's tablets")
       (kalāma superpose "SAG.SAG.SAG = many-headed = all at once")
       (𒊕𒊕𒊕 superpose "SAG.SAG.SAG = many-headed = all at once")
       (kalāma-mitḫārum quantum-uniform "SAG.SAG.DIŠ = all-equal heads")
       (𒊕𒊕𒁹 quantum-uniform "SAG.SAG.DIŠ = all-equal heads")
       (amārum observe "IGI.I = eye-going = to look upon")
       (𒅆𒄿 observe "IGI.I = eye-going = to look upon")
       (kalāma? quantum? "SAG.SAG?")
       (𒊕𒊕? quantum? "SAG.SAG?")
       (kalāma-nindabûm quantum-states "SAG.SAG.UM = all-states-tablet")
       (𒊕𒊕𒌝 quantum-states "SAG.SAG.UM = all-states-tablet")
       (mīnum-kalāma quantum-n "SAG.SAG.I  = count-of-all")
       (𒊕𒊕𒄿 quantum-n "SAG.SAG.I  = count-of-all")
       (epēšum-kibrātim make-mv "KI.GAL.LU2 = great-space-make")
       (𒆠𒃲𒇽 make-mv "KI.GAL.LU2 = great-space-make")
       (kibrātim? mv? "KI.GAL?    = is it a great space?")
       (𒆠𒃲? mv? "KI.GAL?    = is it a great space?")
       (ṣimdat-kibrātim mv-signature "KI.GAL.TAR = space-signature")
       (𒆠𒃲𒋻 mv-signature "KI.GAL.TAR = space-signature")
       (maḫārum-kibrātim mv-ref "KI.GAL.SAG = space-head")
       (𒆠𒃲𒊕 mv-ref "KI.GAL.SAG = space-head")
       (šakānum-kibrātim mv-set! "KI.GAL.DIŠ = place-in-space")
       (𒆠𒃲𒁹 mv-set! "KI.GAL.DIŠ = place-in-space")
       (matāḫum-kibrātim mv+ "KI.GAL.TAR.DIŠ = space-add")
       (𒆠𒃲𒋻𒁹 mv+ "KI.GAL.TAR.DIŠ = space-add")
       (ḫarāṣum-kibrātim mv- "KI.GAL.LAL.UD  = space-subtract")
       (𒆠𒃲𒇲𒌑 mv- "KI.GAL.LAL.UD  = space-subtract")
       (šutakūlum-kibrātim mv* "KI.GAL.MAŠ     = geometric product")
       (𒆠𒃲𒈧 mv* "KI.GAL.MAŠ     = geometric product")
       (zâzum-kibrātim mv-scale "KI.GAL.MAŠ.DIŠ = space-scale")
       (𒆠𒃲𒈧𒁹 mv-scale "KI.GAL.MAŠ.DIŠ = space-scale")
       (ṣilippum-kibrātim mv-wedge "KI.GAL.U  = diagonal/outer product")
       (𒆠𒃲𒌋 mv-wedge "KI.GAL.U  = diagonal/outer product")
       (ṣibûm-kibrātim mv-lcontract "KI.GAL.IB = left-hold of space")
       (𒆠𒃲𒅁 mv-lcontract "KI.GAL.IB = left-hold of space")
       (turrum-kibrātim mv-reverse "KI.GAL.GI.DIŠ  = space-return")
       (𒆠𒃲𒄀𒁹 mv-reverse "KI.GAL.GI.DIŠ  = space-return")
       (nakārum-kibrātim mv-involute "KI.GAL.NU.I    = space-become-other")
       (𒆠𒃲𒉡𒄿 mv-involute "KI.GAL.NU.I    = space-become-other")
       (mitḫurtum-kibrātim mv-conjugate "KI.GAL.MA.TAR  = space-complement")
       (𒆠𒃲𒈠𒋻 mv-conjugate "KI.GAL.MA.TAR  = space-complement")
       (šanûm-kibrātim mv-dual "KI.GAL.BA.A    = the other of space")
       (𒆠𒃲𒁀𒀀 mv-dual "KI.GAL.BA.A    = the other of space")
       (šinīpat-kibrātim mv-grade "KI.GAL.AŠ2 = grade level")
       (𒆠𒃲𒀸 mv-grade "KI.GAL.AŠ2 = grade level")
       (ṣifrum-kibrātim mv-scalar "KI.GAL.NU.NU   = zero-grade = scalar")
       (𒆠𒃲𒉡𒉡 mv-scalar "KI.GAL.NU.NU   = zero-grade = scalar")
       (napḫarum-kibrātim mv-norm2 "KI.GAL.ME.ME   = squared-sum")
       (𒆠𒃲𒈷𒈷 mv-norm2 "KI.GAL.ME.ME   = squared-sum")
       (ibum-kibrātim mv-norm "KI.GAL.IB.DIŠ  = space-side (ibum = square root)")
       (𒆠𒃲𒅁𒁹 mv-norm "KI.GAL.IB.DIŠ  = space-side (ibum = square root)")
       (ibum-ṣīrum-kibrātim mv-normalize "KI.GAL.IB.UD   = supreme-side")
       (𒆠𒃲𒅁𒌑 mv-normalize "KI.GAL.IB.UD   = supreme-side")
       (pānum-kibrātim mv-e "KI.GAL.IGI = face/eye of space = basis blade")
       (𒆠𒃲𒅆 mv-e "KI.GAL.IGI = face/eye of space = basis blade")
       (kibrātim-maḫārum mv-from-list "KI.GAL.UM  = space from tablet")
       (𒆠𒃲𒌝 mv-from-list "KI.GAL.UM  = space from tablet")
       (rebûm-ana-kibrātim quaternion->mv "KI.GAL.EN  = enter the great space")
       (𒆠𒃲𒂗 quaternion->mv "KI.GAL.EN  = enter the great space")
       (kibrātum-ana-rebîm mv->quaternion "KI.GAL.EN.NU = exit space to fourfold")
       (𒆠𒃲𒂗𒉡 mv->quaternion "KI.GAL.EN.NU = exit space to fourfold")
       (epēšum-rebûm make-quaternion "IB.ME  = hold-essence = 4D")
       (𒅁𒈷 make-quaternion "IB.ME  = hold-essence = 4D")
       (rebûm? quaternion? "IB.ME? = is it fourfold?")
       (𒅁𒈷? quaternion? "IB.ME? = is it fourfold?")
       (epēšum-samānûm make-octonion "IB.ME.ME  = double-hold-essence = 8D")
       (𒅁𒈷𒈷 make-octonion "IB.ME.ME  = double-hold-essence = 8D")
       (samānûm? octonion? "IB.ME.ME? = is it eightfold?")
       (𒅁𒈷𒈷? octonion? "IB.ME.ME? = is it eightfold?")
       (maḫārum-samānûm octonion-ref "IB.ME.SAG = eightfold-head")
       (𒅁𒈷𒊕 octonion-ref "IB.ME.SAG = eightfold-head")
       (epēšum-nindabîm make-list "LU2.I.UM = person-going-tablet = make list")
       (𒇽𒄿𒌝 make-list "LU2.I.UM = person-going-tablet = make list")
       (awāt-bīti get-environment-variable "E2.ME = house-essence = one env var")
       (𒂍𒈷 get-environment-variable "E2.ME = house-essence = one env var")
       (awātāt-bīti get-environment-variables "E2.ME.ME = all-house-essences")
       (𒂍𒈷𒈷 get-environment-variables "E2.ME.ME = all-house-essences")
       (aṣûm-dannum emergency-exit "I.GAL = going-great = urgent/forced exit")
       (𒄿𒃲 emergency-exit "I.GAL = going-great = urgent/forced exit")
       (ūmum-ēṭum-inanna current-second "UD.I = day-going = elapsed seconds")
       (𒌑𒄿 current-second "UD.I = day-going = elapsed seconds")
       (ṭarādum-inanna current-jiffy "UD.DIŠ = day-one = one time-beat now")
       (𒌑𒁹 current-jiffy "UD.DIŠ = day-one = one time-beat now")
       (ṭarādū-ina-ūmim jiffies-per-second "UD.UD = beats-per-elapsed analogue")
       (𒌑𒌑 jiffies-per-second "UD.UD = beats-per-elapsed analogue")
       (awāt-ḫiṭītim error-object-message "ḪI.UM = fault-tablet = the error's word")
       (𒄷𒌝 error-object-message "ḪI.UM = fault-tablet = the error's word")
       (ḫiṭītum-šemûm? read-error? "ḪI.IGI? = fault-eye? = reading fault?")
       (𒄷𒅆? read-error? "ḪI.IGI? = fault-eye? = reading fault?")
       (ḫiṭītum-ṭuppi? file-error? "ḪI.E2? = fault-house? = tablet/file fault?")
       (𒄷𒂍? file-error? "ḪI.E2? = fault-house? = tablet/file fault?")
      )))

(set-active-language! "akkadian")
