;;; langs/greek.scm — Ελληνική Κλασική (Classical Greek) language pack for Curry Scheme.
;;;
;;; Classical Greek language pack for Curry Scheme.
;;; 
;;; Ancient Greek is the language of Plato, Aristotle, Euclid, and
;;; Archimedes. Many computing and mathematical concepts have their roots
;;; in Greek: algorithm (from al-Khwarizmi, translating Greek), arithmetic
;;; (ἀριθμός), synthesis, analysis, logic (λόγος), theory (θεωρία), atom
;;; (ἄτομον — indivisible, the exact concept behind atomically!).
;;; 
;;; This pack uses authentic Classical Greek forms. Polytonic Unicode is
;;; used throughout; the Curry reader handles UTF-8 natively.
;;; 
;;; Notable etymologies:
;;;   ἀριθμός (number) → arithmetic
;;;   λόγος (word/reason) → logic, logarithm  
;;;   ὅρος (boundary) → horizon; ὁρίζω (define) = set the horizon
;;;   δύναμις (power) → dynamic; used by Pythagoreans for exponentiation
;;;   ῥητός (rational) = what can be said/expressed — irrational = ἄρρητον
;;;   ἄτομον (atom, indivisible) — Democritus; atomically preserves this
;;;   θεωρέω (observe) = contemplate, see — source of "theory"
;;;
;;; Usage:
;;;   (import (curry lang))
;;;   (lang:load-file! "langs/greek.scm")
;;;   ; or after installing: (lang:install! "greek")

(import (curry lang))

(register-language!
  `((id           . "greek")
    (display-name . "Ελληνική Κλασική (Classical Greek)")
    (intro        . "Χαῖρε! Ἡ Ἑλληνικὴ γλῶσσα ἐνεργός ἐστι.")
    (error-preamble . "Ἁμαρτία μεγάλη:")
    (mappings     .
      ;; (foreign-name  canonical-name  "cultural/conceptual note")
      ((ὁρίζω                                         define                                   "ὁρίζω — I define, determine (cf. horizon)")
      (ποιεῖ                                         lambda                                   "ποιεῖ — it makes/creates (from ποιέω)")
      (εἰ                                            if                                       "εἰ — if (the conditional particle)")
      (ἄρχω                                          begin                                    "ἄρχω — I begin, rule (cf. archon)")
      (τίθει                                         set!                                     "τίθει — place, set (from τίθημι)")
      (ἔστω                                          let                                      "ἔστω — let it be (imperative of εἰμί)")
      (ἔστω-ἑξῆς                                     let*                                     "let in sequence")
      (ἔστω-ἀλλήλοις                                 letrec                                   "let mutually")
      (ἔστω-ἀλλήλοις-ἑξῆς                            letrec*                                  "sequential mutual binding")
      (λέγω                                          quote                                    "λέγω — I say, speak")
      (λέγω-σχεδόν                                   quasiquote                               "say almost")
      (λύω                                           unquote                                  "λύω — I loose, release")
      (λύω-σπείρω                                    unquote-splicing                         "loose and scatter")
      (καί                                           and                                      "καί — and (the most common Greek word)")
      (ἤ                                             or                                       "ἤ — or, than")
      (ὅταν                                          cond                                     "ὅταν — whenever (conditional)")
      (κατά                                          case                                     "κατά — according to, by")
      (ὁπότε                                         when                                     "ὁπότε — whenever")
      (εἰ-μή                                         unless                                   "εἰ μή — if not, unless")
      (πράττω                                        do                                       "πράττω — I do, act (cf. practice)")
      (ὁρίζω-σύνταξιν                                define-syntax                            "define syntax")
      (κανόνες-συντάξεως                             syntax-rules                             "rules of syntax")
      (ὁρίζω-ἀξίας                                   define-values                            "define values")
      (ὁρίζω-εἶδος-λόγου                             define-record-type                       "define a record type (εἶδος = form)")
      (ἀξίαι                                         values                                   "ἀξίαι — values, prices")
      (καλῶ-συνέχειαν                                call/cc                                  "call the continuation")
      (καλῶ-παροῦσαν-συνέχειαν                       call-with-current-continuation           "call with current continuation")
      (εἰσάγω                                        import                                   "εἰσάγω — bring in, import")
      (ἐξάγω                                         export                                   "ἐξάγω — lead out, export")
      (ὁρίζω-βιβλιοθήκην                             define-library                           "define a library (βιβλιοθήκη = book-place)")
      (φυλάττω                                       guard                                    "φυλάττω — I guard, watch")
      (παραμετρίζω                                   parameterize                             "set parameters")
      (περιλαμβάνω                                   include                                  "περιλαμβάνω — include, encompass")
      (ἀναβάλλω                                      delay                                    "ἀναβάλλω — postpone (cf. anabasis)")
      (ἀναβάλλω-βίᾳ                                  delay-force                              "force postponement")
      (γεννάω                                        spawn                                    "γεννάω — beget, create (cf. genesis)")
      (πέμπω                                         send!                                    "πέμπω — I send")
      (δέχομαι                                       receive                                  "δέχομαι — I receive, accept")
      (αὐτός                                         self                                     "αὐτός — self, same (cf. autograph)")
      (συνδέω                                        cons                                     "συνδέω — bind together (cf. syndicate)")
      (κεφαλή                                        car                                      "κεφαλή — head (cf. cephalic)")
      (οὐρά                                          cdr                                      "οὐρά — tail")
      (κατάλογος                                     list                                     "κατάλογος — list, catalogue")
      (μῆκος                                         length                                   "μῆκος — length")
      (προστίθημι                                    append                                   "προστίθημι — add to (cf. prosthetic)")
      (ἀναστρέφω                                     reverse                                  "ἀναστρέφω — turn back, reverse")
      (κατάλογος-λαμβάνω                             list-ref                                 "take from list")
      (κατάλογος-οὐρά                                list-tail                                "tail of list")
      (ἐφαρμόζω                                      map                                      "ἐφαρμόζω — apply to each")
      (ἑκάστου                                       for-each                                 "ἑκάστου — for each")
      (διακρίνω                                      filter                                   "διακρίνω — discern, separate (cf. crisis)")
      (ἐπιλύω-ἀριστερόθεν                            fold-left                                "solve from the left")
      (ἐπιλύω-δεξιόθεν                               fold-right                               "solve from the right")
      (ἐξευρίσκω                                     assoc                                    "ἐξευρίσκω — find out, discover")
      (ἐξευρίσκω-ταὐτόν                              assq                                     "find by identity")
      (μέλος                                         member                                   "μέλος — member, limb")
      (ποιέω-κατάλογον                               make-list                                "make a list")
      (οὐ                                            not                                      "οὐ — not (negation of fact)")
      (ἀληθὴς-ἴσον?                                  boolean=?                                "booleans equal?")
      (ἐπάγω                                         apply                                    "ἐπάγω — apply, bring upon")
      (ἁμαρτία                                       error                                    "ἁμαρτία — mistake, missing the mark")
      (ὑψόω                                          raise                                    "ὑψόω — raise high")
      (μέγιστον                                      max                                      "μέγιστον — greatest")
      (ἐλάχιστον                                     min                                      "ἐλάχιστον — smallest")
      (ἀπόλυτον                                      abs                                      "ἀπόλυτον — absolute, unloosed")
      (μηδέν?                                        zero?                                    "μηδέν — nothing, zero")
      (θετικόν?                                      positive?                                "θετικόν — placed, positive")
      (ἀρνητικόν?                                    negative?                                "ἀρνητικόν — negative")
      (περιττόν?                                     odd?                                     "περιττόν — odd, superfluous (Pythagorean)")
      (ἄρτιον?                                       even?                                    "ἄρτιον — even, complete (Pythagorean)")
      (ἔδαφος                                        floor                                    "ἔδαφος — floor, ground")
      (ὄροφος                                        ceiling                                  "ὄροφος — ceiling, roof")
      (στρογγύλον                                    round                                    "στρογγύλον — rounded, circular")
      (κόπτω                                         truncate                                 "κόπτω — cut off")
      (δύναμις                                       expt                                     "δύναμις — power, potency (Pythagorean)")
      (ῥίζα                                          sqrt                                     "ῥίζα — root (of a plant)")
      (πηλίκον                                       quotient                                 "πηλίκον — quotient (classical math term)")
      (κατάλοιπον                                    remainder                                "κατάλοιπον — what is left over")
      (ὑπόλοιπον                                     modulo                                   "ὑπόλοιπον — residue")
      (μ-κ-δ                                         gcd                                      "μέγιστος κοινός διαιρέτης")
      (ε-κ-π                                         lcm                                      "ἐλάχιστον κοινὸν πολλαπλάσιον")
      (τετράγωνον                                    square                                   "τετράγωνον — square (classical math term)")
      (ἀκέραιος-ἀκριβής?                             exact-integer?                           "exact integer?")
      (τετραγωνική-ῥίζα-ἀκεραίου                     exact-integer-sqrt                       "integer square root")
      (ἀκριβής                                       exact                                    "ἀκριβής — exact, precise")
      (ἀνακριβής                                     inexact                                  "inexact, approximate")
      (ἀριθμός-εἰς-γραφήν                            number->string                           "number to string")
      (γραφή-εἰς-ἀριθμόν                             string->number                           "string to number")
      (πηλίκον-κεκομμένον                            truncate-quotient                        "truncated quotient")
      (κατάλοιπον-κεκομμένον                         truncate-remainder                       "truncated remainder")
      (διαίρεσις-κόπτουσα                            truncate/                                "truncating division")
      (ἡμίτονον                                      sin                                      "ἡμίτονον — sine (half-chord in classical geometry)")
      (συνημίτονον                                   cos                                      "συνημίτονον — cosine")
      (ἐκθετική                                      exp                                      "ἐκθετική — exponential function")
      (λογάριθμος                                    log                                      "λογάριθμος — logarithm")
      (ἀρκτο-εφαπτομένη                              atan                                     "arc tangent")
      (ἀριθμός?                                      number?                                  "ἀριθμός — number")
      (γραφή?                                        string?                                  "γραφή — writing, string of text")
      (σύμβολον?                                     symbol?                                  "σύμβολον — symbol, token")
      (λογικόν?                                      boolean?                                 "λογικόν — logical value")
      (πράξις?                                       procedure?                               "πράξις — action, procedure")
      (φορεύς?                                       vector?                                  "φορεύς — carrier, vector")
      (γράμμα?                                       char?                                    "γράμμα — letter, character")
      (θύρα?                                         port?                                    "θύρα — door, port")
      (ἀκριβής?                                      exact?                                   "exact?")
      (ἀνακριβής?                                    inexact?                                 "inexact?")
      (ἀκέραιος?                                     integer?                                 "ἀκέραιος — integer (classical term)")
      (ῥητός?                                        rational?                                "ῥητός — rational (classical math term)")
      (ἀληθινός?                                     real?                                    "ἀληθινός — true, real")
      (σύνθετος?                                     complex?                                 "σύνθετος — composite, complex")
      (ζεῦγος?                                       pair?                                    "ζεῦγος — pair, yoke")
      (κενόν?                                        null?                                    "κενόν — empty, void (the Void)")
      (κατάλογος?                                    list?                                    "κατάλογος — list")
      (αὐτό?                                         eq?                                      "the very same thing")
      (ἰσοδύναμον?                                   eqv?                                     "of equal power/value")
      (ἴσον?                                         equal?                                   "ἴσον — equal")
      (δείκνυμι                                      display                                  "δείκνυμι — I show (cf. paradigm)")
      (γράφω                                         write                                    "γράφω — I write (cf. graphic)")
      (νέα-γραμμή                                    newline                                  "new line")
      (ἀναγιγνώσκω                                   read                                     "ἀναγιγνώσκω — I read (classical term)")
      (ἀναγιγνώσκω-γραμμήν                           read-line                                "read a line")
      (ἀναγιγνώσκω-γράμμα                            read-char                                "read a character")
      (γράφω-γράμμα                                  write-char                               "write a character")
      (γράφω-γραφήν                                  write-string                             "write a string")
      (ἀνοίγω-ἀρχεῖον-εἰσόδου                        open-input-file                          "open input file")
      (ἀνοίγω-ἀρχεῖον-ἐξόδου                         open-output-file                         "open output file")
      (κλείω-θύραν                                   close-port                               "κλείω — close (cf. cloister)")
      (ἐκκενόω-θύραν                                 flush-output-port                        "flush output port")
      (τέλος-ἀρχείου?                                eof-object?                              "end of file?")
      (γράμμα-ἕτοιμον?                               char-ready?                              "character ready?")
      (ὀκτώ-ἕτοιμον?                                 u8-ready?                                "byte ready?")
      (ἀναγιγνώσκω-ὀκτώ                              read-u8                                  "read byte")
      (βλέπω-ὀκτώ                                    peek-u8                                  "peek at byte")
      (ἀναγιγνώσκω-γραφήν                            read-string                              "read string")
      (ἀναγιγνώσκω-φορέα                             read-bytevector                          "read bytevector")
      (ἀναγιγνώσκω-εἰς-φορέα                         read-bytevector!                         "read into bytevector")
      (γράφω-ὀκτώ                                    write-u8                                 "write byte")
      (γράφω-φορέα                                   write-bytevector                         "write bytevector")
      (γράφω-ἁπλῶς                                   write-simple                             "write simply")
      (ἀρχεῖον-ὑπάρχει?                              file-exists?                             "does file exist?")
      (ἀφαιρέω-ἀρχεῖον                               delete-file                              "ἀφαιρέω — take away, subtract")
      (καλῶ-ἀρχεῖον-εἰσόδου                          call-with-input-file                     "call with input file")
      (καλῶ-ἀρχεῖον-ἐξόδου                           call-with-output-file                    "call with output file")
      (εἴσοδος-ἀπὸ-ἀρχείου                           with-input-from-file                     "with input from file")
      (ἔξοδος-εἰς-ἀρχεῖον                            with-output-to-file                      "with output to file")
      (ἁμαρτία-ἀναγνώσεως?                           read-error?                              "read error?")
      (ἁμαρτία-ἀρχείου?                              file-error?                              "file error?")
      (λόγος-ἁμαρτίας                                error-object-message                     "message of the error")
      (λαμβάνω-μεταβλητήν-περιβάλλοντος              get-environment-variable                 "get environment variable")
      (λαμβάνω-μεταβλητὰς-περιβάλλοντος              get-environment-variables                "get all environment variables")
      (φεύγω-σπουδαίως                               emergency-exit                           "φεύγω — flee in haste")
      (παρὸν-λεπτόν                                  current-second                           "current second")
      (παρὸν-στιγμή                                  current-jiffy                            "current instant")
      (στιγμαὶ-ἀνὰ-λεπτόν                            jiffies-per-second                       "instants per second")
      (ποιέω-γραφήν                                  make-string                              "make a string")
      (γραφή                                         string                                   "γραφή — writing, text")
      (μῆκος-γραφῆς                                  string-length                            "length of string")
      (λαμβάνω-γράμμα                                string-ref                               "take character from string")
      (προστίθημι-γραφήν                             string-append                            "add to string")
      (ἀντιγράφω                                     string-copy                              "ἀντιγράφω — copy (write against)")
      (μέρος-γραφῆς                                  substring                                "part of string")
      (γραφή-εἰς-κατάλογον                           string->list                             "string to list")
      (κατάλογος-εἰς-γραφήν                          list->string                             "list to string")
      (γραφή-μεγαλογράμματα                          string-upcase                            "string to uppercase")
      (γραφή-μικρογράμματα                           string-downcase                          "string to lowercase")
      (γραφή-ἴση?                                    string=?                                 "strings equal?")
      (γραφή-ἐλάττων?                                string<?                                 "string less than?")
      (γραφή-ἐλάττων-ἢ-ἴση?                          string<=?                                "string ≤?")
      (γραφή-μείζων?                                 string>?                                 "string greater?")
      (γραφή-μείζων-ἢ-ἴση?                           string>=?                                "string ≥?")
      (γραφή-ἴση-ἀδιάφορος?                          string-ci=?                              "string = case-insensitive?")
      (γραφή-ἐλάττων-ἀδιάφορος?                      string-ci<?                              "string < case-insensitive?")
      (γραφή-μείζων-ἀδιάφορος?                       string-ci>?                              "string > case-insensitive?")
      (γραφή-ἐλάττων-ἢ-ἴση-ἀδιάφορος?                string-ci<=?                             "string ≤ case-insensitive?")
      (γραφή-μείζων-ἢ-ἴση-ἀδιάφορος?                 string-ci>=?                             "string ≥ case-insensitive?")
      (γραφή-εἰς-σύμβολον                            string->symbol                           "string to symbol")
      (σύμβολον-εἰς-γραφήν                           symbol->string                           "symbol to string")
      (τίθει-γράμμα-γραφῆς                           string-set!                              "set character in string")
      (ἀντιγράφω-εἰς                                 string-copy!                             "copy string into")
      (ἑκάστου-γράμμα                                string-for-each                          "for each character")
      (πληρόω-γραφήν                                 string-fill!                             "fill string")
      (γραφή-ἑνικὸς-χαρακτήρ                         string-foldcase                          "fold string case")
      (γραφή-εἰς-UTF8                                string->utf8                             "string to UTF-8")
      (UTF8-εἰς-γραφήν                               utf8->string                             "UTF-8 to string")
      (γράμμα-εἰς-ἀριθμόν                            char->integer                            "character to integer")
      (ἀριθμός-εἰς-γράμμα                            integer->char                            "integer to character")
      (γράμμα-ἴσον?                                  char=?                                   "characters equal?")
      (γράμμα-ἔλαττον?                               char<?                                   "character less than?")
      (γράμμα-ἔλαττον-ἢ-ἴσον?                        char<=?                                  "char ≤?")
      (γράμμα-μεῖζον?                                char>?                                   "character greater?")
      (γράμμα-μεῖζον-ἢ-ἴσον?                         char>=?                                  "char ≥?")
      (γράμμα-ἴσον-ἀδιάφορος?                        char-ci=?                                "char = case-insensitive?")
      (γράμμα-ἔλαττον-ἀδιάφορος?                     char-ci<?                                "char < case-insensitive?")
      (γράμμα-μεῖζον-ἀδιάφορος?                      char-ci>?                                "char > case-insensitive?")
      (γράμμα-ἔλαττον-ἢ-ἴσον-ἀδιάφορος?              char-ci<=?                               "char ≤ case-insensitive?")
      (γράμμα-μεῖζον-ἢ-ἴσον-ἀδιάφορος?               char-ci>=?                               "char ≥ case-insensitive?")
      (ψῆφος-ἀξία                                    digit-value                              "numeric value of digit")
      (γράμμα-ἑνικὸς-χαρακτήρ                        char-foldcase                            "fold character case")
      (ποιέω-φορέα                                   make-vector                              "make a vector")
      (φορεύς                                        vector                                   "φορεύς — carrier, vector")
      (μῆκος-φορέος                                  vector-length                            "length of vector")
      (λαμβάνω-φορέος                                vector-ref                               "take from vector")
      (τίθει-φορέα                                   vector-set!                              "set element of vector")
      (φορεύς-εἰς-κατάλογον                          vector->list                             "vector to list")
      (κατάλογος-εἰς-φορέα                           list->vector                             "list to vector")
      (πληρόω-φορέα                                  vector-fill!                             "fill vector")
      (ἀντιγράφω-φορέα                               vector-copy                              "copy vector")
      (ἐφαρμόζω-φορέα                                vector-map                               "map over vector")
      (ἑκάστου-φορέος                                vector-for-each                          "for each in vector")
      (προστίθημι-φορέα                              vector-append                            "append vectors")
      (ἀντιγράφω-εἰς-φορέα                           vector-copy!                             "copy into vector")
      (ποιέω-ὀκτάφορον                               make-bytevector                          "make bytevector")
      (ὀκτάφορον                                     bytevector                               "eight-bit carrier")
      (μῆκος-ὀκτάφορου                               bytevector-length                        "length of bytevector")
      (λαμβάνω-ὀκτάφορου                             bytevector-u8-ref                        "byte ref")
      (τίθει-ὀκτάφορον                               bytevector-u8-set!                       "set byte")
      (ἀντιγράφω-ὀκτάφορον                           bytevector-copy                          "copy bytevector")
      (ἀντιγράφω-εἰς-ὀκτάφορον                       bytevector-copy!                         "copy into bytevector")
      (προστίθημι-ὀκτάφορον                          bytevector-append                        "append bytevectors")
      (συμβολικὴ-μεταβλητή                           sym-var                                  "symbolic variable")
      (συμβολικὴ-μεταβλητή?                          sym-var?                                 "is symbolic variable?")
      (συμβολικὴ-ἔκφρασις?                           sym-expr?                                "is symbolic expression?")
      (συμβολικόν?                                   symbolic?                                "is symbolic?")
      (ὄνομα-μεταβλητῆς                              sym-var-name                             "name of variable")
      (ὑπόθεσις-μεταβλητῆς?                          sym-assumption?                          "has assumption?")
      (συμβολικὴ-διαφορά                             sym-diff                                 "symbolic differentiation")
      (κλασματικὴ-διαφορά                            frac-diff                                "fractional differentiation")
      (Wirtinger-δ                                   wirtinger-d                              "Wirtinger derivative ∂/∂z")
      (Wirtinger-δ-ταύτης                            wirtinger-dbar                           "Wirtinger conjugate derivative")
      (αὐτόματη-διαφορά                              auto-diff                                "automatic differentiation")
      (ὁλοκλήρωσις                                   integrate                                "ὁλοκλήρωσις — integration (making whole)")
      (κλασματικὴ-ὁλοκλήρωσις                        frac-int                                 "fractional integration")
      (ἁπλουστεύω                                    simplify                                 "ἁπλουστεύω — simplify, make simple")
      (ἀντικαθίστημι                                 substitute                               "ἀντικαθίστημι — substitute (cf. antihistamine)")
      (εὐρύνω                                        expand                                   "εὐρύνω — widen, expand")
      (βαθμός                                        degree                                   "βαθμός — step, degree")
      (συλλέγω                                       collect                                  "συλλέγω — collect (cf. syllogism)")
      (πρῶτος-συντελεστής                            leading-coeff                            "leading coefficient")
      (συζυγής                                       conjugate                                "συζυγής — conjugate, yoked together")
      (σύντομος-συζυγής                              conj                                     "conjugate (short form)")
      (συμβολικόν-εἰς-γραφήν                         sym->string                              "symbolic expression to string")
      (σύμβολον-εἰς-μέσον                            sym->infix                               "symbolic to infix")
      (σύμβολον-εἰς-λατινικά                         sym->latex                               "symbolic to LaTeX")
      (ὑπεραληθινόν?                                 surreal?                                 "beyond real")
      (ὑπεραληθινόν-ἄπειρον?                         surreal-infinite?                        "surreal infinite?")
      (ὑπεραληθινόν-πεπερασμένον?                    surreal-finite?                          "surreal finite?")
      (ὑπεραληθινόν-ἀπειροστόν?                      surreal-infinitesimal?                   "surreal infinitesimal?")
      (ἀληθινὸν-μέρος                                surreal-real-part                        "real part")
      (μέρος-ὠμέγα                                   surreal-omega-part                       "omega part")
      (μέρος-ἐψιλόν                                  surreal-epsilon-part                     "epsilon part")
      (γενέθλιον                                     surreal-birthday                         "γενέθλιον — birthday (classical term)")
      (πλῆθος-ὅρων                                   surreal-nterms                           "number of terms")
      (ὑπεραληθινόν-εἰς-ἀριθμόν                      surreal->number                          "surreal to number")
      (ποιέω-ὑπεραληθινόν                            make-surreal                             "make surreal number")
      (ὅροι-ὑπεραληθινοῦ                             surreal-terms                            "terms of surreal")
      (ἐπαλλάττω                                     superpose                                "ἐπαλλάττω — interleave, superpose")
      (κβαντικὸν-ὁμαλόν                              quantum-uniform                          "uniform quantum distribution")
      (θεωρέω                                        observe                                  "θεωρέω — contemplate (source of 'theory')")
      (κβαντικόν?                                    quantum?                                 "κβαντικόν — quantum")
      (κβαντικαὶ-καταστάσεις                         quantum-states                           "quantum states")
      (ἀριθμὸς-κβαντικῶν                             quantum-n                                "number of quantum branches")
      (ποιέω-πολυφορέα                               make-mv                                  "make multivector")
      (πολυφορεύς?                                   mv?                                      "is multivector?")
      (σφραγὶς-πολυφορέος                            mv-signature                             "Clifford signature")
      (λαμβάνω-πολυφορέος                            mv-ref                                   "multivector blade ref")
      (τίθει-πολυφορέα                               mv-set!                                  "set multivector component")
      (πολυφορεύς+                                   mv+                                      "multivector addition")
      (πολυφορεύς-                                   mv-                                      "multivector subtraction")
      (πολυφορεύς*                                   mv*                                      "geometric product")
      (κλιμακόω-πολυφορέα                            mv-scale                                 "scale multivector")
      (σφήν-πολυφορέος                               mv-wedge                                 "wedge product (exterior)")
      (συστολὴ-ἀριστερά                              mv-lcontract                             "left contraction")
      (ἀναστρέφω-πολυφορέα                           mv-reverse                               "reverse multivector")
      (ἑλίττω-πολυφορέα                              mv-involute                              "involute")
      (συζυγὴς-πολυφορεύς                            mv-conjugate                             "Clifford conjugate")
      (διπλοῦς-πολυφορεύς                            mv-dual                                  "dual multivector")
      (βαθμὸς-πολυφορέος                             mv-grade                                 "grade projection")
      (σκαλαρὶς-πολυφορεύς                           mv-scalar                                "scalar part")
      (νόρμα²-πολυφορέος                             mv-norm2                                 "squared norm")
      (νόρμα-πολυφορέος                              mv-norm                                  "norm")
      (κανονίζω-πολυφορέα                            mv-normalize                             "normalize")
      (ε-πολυφορεύς                                  mv-e                                     "basis blade constructor")
      (πολυφορεύς-ἐκ-καταλόγου                       mv-from-list                             "multivector from list")
      (τετράδα-εἰς-πολυφορέα                         quaternion->mv                           "quaternion to multivector")
      (πολυφορεύς-εἰς-τετράδα                        mv->quaternion                           "multivector to quaternion")
      (ποιέω-τετράδα                                 make-quaternion                          "τετράς — quaternion (group of four)")
      (τετράς?                                       quaternion?                              "is quaternion?")
      (ποιέω-ὀκτάδα                                  make-octonion                            "ὀκτάς — octonion (group of eight)")
      (ὀκτάς?                                        octonion?                                "is octonion?")
      (λαμβάνω-ὀκτάδος                               octonion-ref                             "octonion component")
      (ὑποκριτὴς-ζῇ?                                 actor-alive?                             "ὑποκριτής — actor (one who interprets)")
      (ῥητὸς-εἰς-ἑξηκοντάδα                          rational->sexagesimal                    "rational to Babylonian sexagesimal")
      (ἑξηκοντάδα-εἰς-ῥητόν                          sexagesimal->rational                    "sexagesimal to rational")
      (ὧρες-εἰς-λεπτά                                hms->seconds                             "hours-minutes-seconds to seconds")
      (λεπτὰ-εἰς-ὧρες                                seconds->hms                             "seconds to HMS")
      (μοῖρες-εἰς-δεκαδικάς                          dms->degrees                             "degrees-minutes-seconds to decimal")
      (δεκαδικαὶ-εἰς-μοίρας                          degrees->dms                             "decimal to DMS")
      (παροῦσα-σημειογραφία                          current-number-notation                  "current number notation")
      (ποιέω-μεταβλητήν-συναλλαγῆς                   make-tvar                                "make transactional variable")
      (λέγε-μεταβλητήν-συναλλαγῆς                    tvar-read                                "read tvar")
      (γράφε-μεταβλητήν-συναλλαγῆς                   tvar-write!                              "write tvar")
      (ἀτομικῶς                                      atomically                               "ἄτομος — indivisible (Democritus!)")
      (ὁμόχρονοι-πυρῆνες                             hardware-concurrency                     "number of parallel cores")
      (ἑκάστου-ὁμόχρονος                             for-each/par                             "parallel for-each")
      (ἀναλύω                                        reduce                                   "ἀναλύω — analyse, reduce")
      (βαθμωτήρ                                      grad                                     "gradient")
      (ἀπόκλισις                                     divergence                               "divergence")
      (στρόβιλος                                     curl                                     "curl, whirlpool")
      (Λαπλάσιος                                     laplacian                                "Laplacian operator")
      (σημειακὸν-γινόμενον                           dot-product                              "dot product")
      (διασταυρωτικὸν-γινόμενον                      cross-product                            "cross product")
      (πέρας                                         limit                                    "πέρας — limit, end (cf. perigee)")
      (Δ                                             D                                        "differential operator")
      (μερικὴ-διαφορά                                partial                                  "partial derivative")
      (σημεῖον                                       sign                                     "σημεῖον — sign, mark (cf. semiotic)")
      (τυχαῖος-ἀριθμός                               random-integer                           "random integer")
      (τυχαῖος-ἀληθινός                              random-real                              "random real number")
      (στατιστικαὶ-ὑποκριτοῦ                         actor-stats                              "actor statistics")
      (ταυτότης-ὑποκριτοῦ                            actor-id                                 "actor identifier")
      (ἀόριστον?                                     unspecified?                             "unspecified?")
      (ἄνω                                           up                                       "up-tuple (contravariant)")
      (κάτω                                          down                                     "down-tuple (covariant)")
      (ἄνω?                                          up?                                      "is up-tuple?")
      (κάτω?                                         down?                                    "is down-tuple?")
      (σύστοιχον?                                    tuple?                                   "is tuple?")
      (λαμβάνω                                       ref                                      "reference/take")
      (διάστασις                                     dimension                                "διάστασις — dimension")
      ))))

;; To activate: (set-active-language! "greek")
