;;; langs/irish.scm — Gaeilge (Modern Irish) language pack for Curry Scheme.
;;;
;;; Modern Irish (Gaeilge) language pack for Curry Scheme.
;;; 
;;; Irish is one of the oldest living languages in Europe, with a literary
;;; tradition stretching back 1500 years. This pack maps Curry's built-in
;;; names to idiomatic Modern Irish equivalents, letting young people in
;;; Gaeltacht communities and Irish-medium schools (Gaelscoileanna) write
;;; programs in their native language.
;;; 
;;; Concept mappings note: Irish has rich vocabulary for abstract ideas.
;;;   feidhm (lambda) = function, use, purpose
;;;   ceann/eireaball (car/cdr) = head/tail — natural Irish metaphors
;;;   scag (filter) = to sieve — the Irish sieve is an ancient implement
;;;   beir (spawn) = to carry, give birth — actors are born, not made
;;;   taispeáin (display) = to show, make visible
;;;
;;; Usage:
;;;   (import (curry lang))
;;;   (lang:load-file! "langs/irish.scm")
;;;   ; or after installing: (lang:install! "irish")

(import (curry lang))

(register-language!
  `((id           . "irish")
    (display-name . "Gaeilge (Modern Irish)")
    (intro        . "Fáilte! Tá an Ghaeilge gníomhach anois.")
    (error-preamble . "Earráid mhór:")
    (mappings     .
      ;; (foreign-name  canonical-name  "cultural/conceptual note")
      ((sainmhínigh                                   define                                   "sainmhíniú — give a precise definition")
      (feidhm                                        lambda                                   "feidhm — function, that which acts")
      (má                                            if                                       "má — if, the conditional")
      (tosaigh                                       begin                                    "tosú — beginning, start")
      (socraigh                                      set!                                     "socrú — settle, set in place")
      (lig                                           let                                      "ligean — allow, let")
      (lig-i-ndiaidh                                 let*                                     "sequential binding")
      (lig-chéile                                    letrec                                   "mutual binding")
      (lig-chéile-i-ndiaidh                          letrec*                                  "sequential mutual binding")
      (luaigh                                        quote                                    "luadh — cite, quote")
      (beagnach-luaigh                               quasiquote                               "almost-quote")
      (díluaigh                                      unquote                                  "un-quote")
      (díluaigh-sceite                               unquote-splicing                         "spliced un-quote")
      (agus                                          and                                      "agus — and")
      (nó                                            or                                       "nó — or")
      (coinníoll                                     cond                                     "coinníoll — condition")
      (cás                                           case                                     "cás — case")
      (nuair                                         when                                     "nuair — when")
      (mura                                          unless                                   "mura — unless, if not")
      (déan                                          do                                       "déanamh — do, make")
      (sainmhínigh-comhréir                          define-syntax                            "define syntax")
      (rialacha-comhréire                            syntax-rules                             "rules of syntax")
      (sainmhínigh-luachanna                         define-values                            "define multiple values")
      (sainmhínigh-cineál-taifid                     define-record-type                       "define a record type")
      (luachanna                                     values                                   "luachanna — values")
      (glaoigh-ar-leanúint                           call/cc                                  "call with continuation")
      (glaoigh-le-leanúint-reatha                    call-with-current-continuation           "call with current continuation")
      (iompórtáil                                    import                                   "bring in from elsewhere")
      (easpórtáil                                    export                                   "send out to others")
      (sainmhínigh-leabharlann                       define-library                           "define a module/library")
      (cosain                                        guard                                    "cosaint — protect, guard")
      (paraiméadrigh                                 parameterize                             "set dynamic parameters")
      (áirigh                                        include                                  "áireamh — include, count")
      (moilligh                                      delay                                    "moilliú — delay, postpone")
      (moilligh-fórsa                                delay-force                              "force-delay")
      (beir                                          spawn                                    "beir — give birth, spawn a new actor")
      (seol                                          send!                                    "seol — send, as a ship sails")
      (faigh-teachtaireacht                          receive                                  "receive a message")
      (féin                                          self                                     "féin — self, oneself")
      (cónasc                                        cons                                     "cónasc — link, join")
      (ceann                                         car                                      "ceann — head, first")
      (eireaball                                     cdr                                      "eireaball — tail")
      (liosta                                        list                                     "liosta — list")
      (fad                                           length                                   "fad — length")
      (cuir-le                                       append                                   "add to, append")
      (inbhéartaigh                                  reverse                                  "invert, reverse")
      (tagairt-liosta                                list-ref                                 "reference into list")
      (eireaball-liosta                              list-tail                                "tail of list")
      (mapáil                                        map                                      "apply across each element")
      (do-gach                                       for-each                                 "do for each element")
      (scag                                          filter                                   "scagadh — sieve, filter")
      (fill-clé                                      fold-left                                "fold from the left")
      (fill-deas                                     fold-right                               "fold from the right")
      (comhlachas                                    assoc                                    "association, lookup")
      (comhlachas-c                                  assq                                     "association by identity")
      (ball                                          member                                   "ball — member")
      (cruthaigh-liosta                              make-list                                "create a new list")
      (ní                                            not                                      "ní — is not, negation")
      (boolach-ionann?                               boolean=?                                "booleans equal?")
      (cuir-i-bhfeidhm                               apply                                    "put into effect")
      (earráid                                       error                                    "earráid — mistake, error")
      (ardaigh                                       raise                                    "ardú — raise, lift")
      (uasmhéid                                      max                                      "maximum")
      (íosmhéid                                      min                                      "minimum")
      (dearbhluach                                   abs                                      "absolute value")
      (náid?                                         zero?                                    "náid — zero")
      (dearfach?                                     positive?                                "dearfach — positive, affirmative")
      (diúltach?                                     negative?                                "diúltach — negative, refusing")
      (corr?                                         odd?                                     "corr — odd, uneven")
      (cothrom?                                      even?                                    "cothrom — even, balanced")
      (urlár                                         floor                                    "urlár — floor")
      (síleáil                                       ceiling                                  "síleáil — ceiling")
      (slánaigh                                      round                                    "round to whole number")
      (gearr                                         truncate                                 "gearr — cut short, truncate")
      (cumhacht                                      expt                                     "cumhacht — power, strength")
      (fréamh-chearnach                              sqrt                                     "fréamh — root (of a plant)")
      (caití                                         quotient                                 "caití — quotient")
      (iarmhar                                       remainder                                "iarmhar — remainder, leftover")
      (modúló                                        modulo                                   "modulo")
      (mcd                                           gcd                                      "mórmhéid choiteann roinnte")
      (lcc                                           lcm                                      "luach coiteann is lú")
      (cearnóg                                       square                                   "cearnóg — square")
      (slánuimhir-bheacht?                           exact-integer?                           "exact integer?")
      (fréamh-slánuimhir                             exact-integer-sqrt                       "integer square root")
      (beacht                                        exact                                    "beacht — exact, precise")
      (míbheacht                                     inexact                                  "inexact, approximate")
      (uimhir->teaghrán                              number->string                           "number to string")
      (teaghrán->uimhir                              string->number                           "string to number")
      (caití-ghearrtha                               truncate-quotient                        "truncated quotient")
      (iarmhar-ghearrtha                             truncate-remainder                       "truncated remainder")
      (roint-ghearrtha                               truncate/                                "truncating division")
      (sín                                           sin                                      "sín — sine")
      (cós                                           cos                                      "cós — cosine")
      (eas                                           exp                                      "eas — exponential (eas = waterfall)")
      (loga                                          log                                      "loga — logarithm")
      (arc-tán                                       atan                                     "arc tangent")
      (uimhir?                                       number?                                  "uimhir — number")
      (teaghrán?                                     string?                                  "teaghrán — string, thread")
      (siombail?                                     symbol?                                  "siombail — symbol")
      (boolach?                                      boolean?                                 "true or false")
      (nós?                                          procedure?                               "nós — custom, procedure")
      (veicteoir?                                    vector?                                  "veicteoir — vector")
      (carachtar?                                    char?                                    "carachtar — character")
      (port?                                         port?                                    "port — port, gateway")
      (beacht?                                       exact?                                   "exact?")
      (míbheacht?                                    inexact?                                 "inexact?")
      (slánuimhir?                                   integer?                                 "slánuimhir — whole number")
      (réasúnach?                                    rational?                                "réasúnach — rational")
      (fíoruimhir?                                   real?                                    "fíoruimhir — real number")
      (casta?                                        complex?                                 "casta — complex, complicated")
      (péire?                                        pair?                                    "péire — pair")
      (folamh?                                       null?                                    "folamh — empty, null")
      (liosta?                                       list?                                    "liosta — list")
      (ionann?                                       eq?                                      "ionann — same, identical")
      (coibhéiseach?                                 eqv?                                     "coibhéis — equivalent")
      (cothrom?                                      equal?                                   "cothrom — equal, level")
      (taispeáin                                     display                                  "taispeáin — show, display")
      (scríobh                                       write                                    "scríobh — write")
      (líne-nua                                      newline                                  "new line")
      (léigh                                         read                                     "léigh — read")
      (léigh-líne                                    read-line                                "read a line")
      (léigh-carachtar                               read-char                                "read a character")
      (scríobh-carachtar                             write-char                               "write a character")
      (scríobh-teaghrán                              write-string                             "write a string")
      (oscail-comhad-ionchuir                        open-input-file                          "open file for reading")
      (oscail-comhad-aschur                          open-output-file                         "open file for writing")
      (dún-port                                      close-port                               "dún — close, shut")
      (scaoil-port-aschur                            flush-output-port                        "flush output port")
      (deireadh-comhaid?                             eof-object?                              "end of file?")
      (carachtar-réidh?                              char-ready?                              "character ready?")
      (beart-réidh?                                  u8-ready?                                "byte ready?")
      (léigh-beart                                   read-u8                                  "read byte")
      (feach-beart                                   peek-u8                                  "peek at byte")
      (léigh-teaghrán                                read-string                              "read string")
      (léigh-beartveicteoir                          read-bytevector                          "read bytevector")
      (léigh-beartveicteoir!                         read-bytevector!                         "read into bytevector")
      (scríobh-beart                                 write-u8                                 "write byte")
      (scríobh-beartveicteoir                        write-bytevector                         "write bytevector")
      (scríobh-simplí                                write-simple                             "write simply")
      (comhad-ann?                                   file-exists?                             "does file exist?")
      (scrios-comhad                                 delete-file                              "scrios — destroy, delete")
      (glaoigh-comhad-ionchuir                       call-with-input-file                     "call with input file")
      (glaoigh-comhad-aschur                         call-with-output-file                    "call with output file")
      (ionchur-ó-chomhad                             with-input-from-file                     "with input from file")
      (aschur-go-comhad                              with-output-to-file                      "with output to file")
      (earráid-léitheoireachta?                      read-error?                              "read error?")
      (earráid-comhaid?                              file-error?                              "file error?")
      (teachtaireacht-earráide                       error-object-message                     "message of an error")
      (faigh-athróg-timpeallachta                    get-environment-variable                 "get environment variable")
      (faigh-athróga-timpeallachta                   get-environment-variables                "get all environment variables")
      (éalú-éigeandála                               emergency-exit                           "éalú — escape, emergency exit")
      (soicind-reatha                                current-second                           "current second")
      (nóiméad-beag-reatha                           current-jiffy                            "current jiffy")
      (nóiméid-beaga-sa-soicind                      jiffies-per-second                       "jiffies per second")
      (cruthaigh-teaghrán                            make-string                              "cruthaigh — create, make")
      (teaghrán                                      string                                   "teaghrán — string, thread")
      (fad-teaghrán                                  string-length                            "length of string")
      (tagairt-teaghrán                              string-ref                               "reference into string")
      (ceangail-teaghrán                             string-append                            "join strings")
      (cóip-teaghrán                                 string-copy                              "copy string")
      (fo-theaghrán                                  substring                                "sub-string")
      (teaghrán->liosta                              string->list                             "string to list")
      (liosta->teaghrán                              list->string                             "list to string")
      (teaghrán-cásanna-uachtaracha                  string-upcase                            "uppercase string")
      (teaghrán-cásanna-íochtaracha                  string-downcase                          "lowercase string")
      (teaghrán-ionann?                              string=?                                 "strings equal?")
      (teaghrán-níos-lú?                             string<?                                 "string less than?")
      (teaghrán-níos-lú-nó-ionann?                   string<=?                                "string ≤?")
      (teaghrán-níos-mó?                             string>?                                 "string greater than?")
      (teaghrán-níos-mó-nó-ionann?                   string>=?                                "string ≥?")
      (teaghrán-ci-ionann?                           string-ci=?                              "string equal case-insensitive?")
      (teaghrán-ci-níos-lú?                          string-ci<?                              "string < case-insensitive?")
      (teaghrán-ci-níos-mó?                          string-ci>?                              "string > case-insensitive?")
      (teaghrán-ci-lú-nó-ionann?                     string-ci<=?                             "string ≤ case-insensitive?")
      (teaghrán-ci-mó-nó-ionann?                     string-ci>=?                             "string ≥ case-insensitive?")
      (teaghrán->siombail                            string->symbol                           "string to symbol")
      (siombail->teaghrán                            symbol->string                           "symbol to string")
      (socraigh-carachtar-teaghrán                   string-set!                              "set character in string")
      (cóip-teaghrán-ina                             string-copy!                             "copy string into")
      (do-gach-carachtar                             string-for-each                          "for each character")
      (líon-teaghrán                                 string-fill!                             "fill string")
      (teaghrán-aon-chás                             string-foldcase                          "fold string case")
      (teaghrán->utf8                                string->utf8                             "string to UTF-8 bytes")
      (utf8->teaghrán                                utf8->string                             "UTF-8 bytes to string")
      (carachtar->uimhir                             char->integer                            "character to integer")
      (uimhir->carachtar                             integer->char                            "integer to character")
      (carachtar-ionann?                             char=?                                   "characters equal?")
      (carachtar-níos-lú?                            char<?                                   "character less than?")
      (carachtar-lú-nó-ionann?                       char<=?                                  "character ≤?")
      (carachtar-níos-mó?                            char>?                                   "character greater than?")
      (carachtar-mó-nó-ionann?                       char>=?                                  "character ≥?")
      (carachtar-ci-ionann?                          char-ci=?                                "char = case-insensitive?")
      (carachtar-ci-níos-lú?                         char-ci<?                                "char < case-insensitive?")
      (carachtar-ci-níos-mó?                         char-ci>?                                "char > case-insensitive?")
      (carachtar-ci-lú-nó-ionann?                    char-ci<=?                               "char ≤ case-insensitive?")
      (carachtar-ci-mó-nó-ionann?                    char-ci>=?                               "char ≥ case-insensitive?")
      (luach-digit                                   digit-value                              "numeric value of digit character")
      (carachtar-aon-chás                            char-foldcase                            "fold character case")
      (cruthaigh-veicteoir                           make-vector                              "create vector")
      (veicteoir                                     vector                                   "veicteoir — vector")
      (fad-veicteoir                                 vector-length                            "length of vector")
      (tagairt-veicteoir                             vector-ref                               "reference into vector")
      (socraigh-veicteoir                            vector-set!                              "set element of vector")
      (veicteoir->liosta                             vector->list                             "vector to list")
      (liosta->veicteoir                             list->vector                             "list to vector")
      (líon-veicteoir                                vector-fill!                             "fill vector")
      (cóip-veicteoir                                vector-copy                              "copy vector")
      (mapáil-veicteoir                              vector-map                               "map over vector")
      (do-gach-veicteoir                             vector-for-each                          "for each in vector")
      (ceangail-veicteoir                            vector-append                            "append vectors")
      (cóip-veicteoir-ina                            vector-copy!                             "copy vector into")
      (cruthaigh-beartveicteoir                      make-bytevector                          "create bytevector")
      (beartveicteoir                                bytevector                               "beartveicteoir — bytevector")
      (fad-beartveicteoir                            bytevector-length                        "length of bytevector")
      (tagairt-beartveicteoir                        bytevector-u8-ref                        "byte ref")
      (socraigh-beartveicteoir                       bytevector-u8-set!                       "set byte")
      (cóip-beartveicteoir                           bytevector-copy                          "copy bytevector")
      (cóip-beartveicteoir-ina                       bytevector-copy!                         "copy into bytevector")
      (ceangail-beartveicteoir                       bytevector-append                        "append bytevectors")
      (athróg-siombailí                              sym-var                                  "symbolic variable")
      (athróg-siombailí?                             sym-var?                                 "is symbolic variable?")
      (slonn-siombailí?                              sym-expr?                                "is symbolic expression?")
      (siombailí?                                    symbolic?                                "is symbolic?")
      (ainm-athróige                                 sym-var-name                             "name of symbolic variable")
      (toimhde-athróige?                             sym-assumption?                          "has assumption?")
      (difreáil-siombailí                            sym-diff                                 "symbolic differentiation")
      (difreáil-chodánaí                             frac-diff                                "fractional differentiation")
      (d-wirtinger                                   wirtinger-d                              "Wirtinger derivative ∂/∂z")
      (d-ath-wirtinger                               wirtinger-dbar                           "Wirtinger conjugate derivative")
      (uath-difreáil                                 auto-diff                                "automatic differentiation")
      (comhtháthú                                    integrate                                "comhtháthú — integration")
      (comhtháthú-chodánaí                           frac-int                                 "fractional integration")
      (simpliú                                       simplify                                 "simpliú — simplification")
      (ionadaigh                                     substitute                               "ionadú — substitute, replace")
      (leath                                         expand                                   "leathadh — spread out, expand")
      (céim                                          degree                                   "céim — degree, step")
      (bailigh                                       collect                                  "bailiú — collect, gather")
      (comh-éifeacht-ceannasach                      leading-coeff                            "leading coefficient")
      (comhiomálta                                   conjugate                                "complex conjugate")
      (comhiomálta                                   conj                                     "complex conjugate (short)")
      (siombailí->teaghrán                           sym->string                              "symbolic expression to string")
      (siombailí->inmheánach                         sym->infix                               "symbolic to infix notation")
      (siombailí->latex                              sym->latex                               "symbolic to LaTeX")
      (sárshaolta?                                   surreal?                                 "sárshaol — surreal world")
      (sárshaolta-éigríochta?                        surreal-infinite?                        "surreal infinite?")
      (sárshaolta-críochta?                          surreal-finite?                          "surreal finite?")
      (sárshaolta-infínitéiseamach?                  surreal-infinitesimal?                   "surreal infinitesimal?")
      (cuid-fhíor-sárshaolta                         surreal-real-part                        "real part of surreal")
      (cuid-óimheaga-sárshaolta                      surreal-omega-part                       "omega part of surreal")
      (cuid-eipsilón-sárshaolta                      surreal-epsilon-part                     "epsilon part of surreal")
      (breithlá-sárshaolta                           surreal-birthday                         "birthday of surreal number")
      (líon-téarmaí-sárshaolta                       surreal-nterms                           "number of terms")
      (sárshaolta->uimhir                            surreal->number                          "surreal to number")
      (cruthaigh-sárshaolta                          make-surreal                             "create surreal number")
      (téarmaí-sárshaolta                            surreal-terms                            "terms of surreal")
      (forleag                                       superpose                                "forleagan — superposition")
      (candamach-aonfhoirmeach                       quantum-uniform                          "uniform quantum superposition")
      (breathnaigh                                   observe                                  "breathnaí — observe, watch")
      (candamach?                                    quantum?                                 "candamach — quantum")
      (staid-candamacha                              quantum-states                           "quantum states")
      (n-candamach                                   quantum-n                                "number of quantum branches")
      (cruthaigh-iltreoir                            make-mv                                  "create multivector")
      (iltreoir?                                     mv?                                      "iltreoir — multivector")
      (síniú-iltreora                                mv-signature                             "signature of Clifford algebra")
      (tagairt-iltreora                              mv-ref                                   "multivector blade reference")
      (socraigh-iltreoir                             mv-set!                                  "set multivector component")
      (iltreoir+                                     mv+                                      "multivector addition")
      (iltreoir-                                     mv-                                      "multivector subtraction")
      (iltreoir*                                     mv*                                      "geometric product")
      (scálaigh-iltreoir                             mv-scale                                 "scale multivector")
      (iltreoir-uing                                 mv-wedge                                 "wedge (exterior) product")
      (conraigh-clé-iltreoir                         mv-lcontract                             "left contraction")
      (inbhéartaigh-iltreoir                         mv-reverse                               "reverse of multivector")
      (inviliúit-iltreoir                            mv-involute                              "involution of multivector")
      (comhiomálta-iltreoir                          mv-conjugate                             "Clifford conjugate")
      (dé-iltreoir                                   mv-dual                                  "dual of multivector")
      (grád-iltreoir                                 mv-grade                                 "grade projection")
      (scálár-iltreoir                               mv-scalar                                "scalar part")
      (norm2-iltreoir                                mv-norm2                                 "squared norm")
      (norm-iltreoir                                 mv-norm                                  "norm of multivector")
      (normalúigh-iltreoir                           mv-normalize                             "normalize multivector")
      (e-iltreoir                                    mv-e                                     "basis blade constructor")
      (iltreoir-ó-liosta                             mv-from-list                             "multivector from list")
      (ceatharán->iltreoir                           quaternion->mv                           "quaternion to multivector")
      (iltreoir->ceatharán                           mv->quaternion                           "multivector to quaternion")
      (cruthaigh-ceatharán                           make-quaternion                          "ceatharán — quaternion (four-part)")
      (ceatharán?                                    quaternion?                              "is quaternion?")
      (cruthaigh-ochtan                              make-octonion                            "ochtan — octonion (eight-part)")
      (ochtan?                                       octonion?                                "is octonion?")
      (tagairt-ochtan                                octonion-ref                             "octonion component")
      (aisteoír-beo?                                 actor-alive?                             "is actor still alive?")
      (réasúnach->seasagaisimil                      rational->sexagesimal                    "rational to Babylonian base-60")
      (seasagaisimil->réasúnach                      sexagesimal->rational                    "Babylonian base-60 to rational")
      (ucs->soicindí                                 hms->seconds                             "hours-minutes-seconds to seconds")
      (soicindí->ucs                                 seconds->hms                             "seconds to hours-minutes-seconds")
      (cnnm->céimeanna                               dms->degrees                             "degrees-minutes-seconds to decimal degrees")
      (céimeanna->cnnm                               degrees->dms                             "decimal degrees to degrees-minutes-seconds")
      (notáil-reatha                                 current-number-notation                  "current number display notation")
      (cruthaigh-athróg-idirbheart                   make-tvar                                "create transactional variable")
      (léigh-athróg-idirbheart                       tvar-read                                "read transactional variable")
      (scríobh-athróg-idirbheart                     tvar-write!                              "write transactional variable")
      (go-adamhach                                   atomically                               "execute atomically in a transaction")
      (comhthráthacht-crua                           hardware-concurrency                     "number of hardware threads")
      (do-gach-comhthráthach                         for-each/par                             "parallel for-each")
      (laghdaigh                                     reduce                                   "laghdú — reduce, diminish")
      (grádán                                        grad                                     "gradient")
      (cóimhroinnt                                   divergence                               "divergence")
      (casadh                                        curl                                     "curl (vector calculus)")
      (laplaisian                                    laplacian                                "Laplacian operator")
      (táirgeadh-ponc                                dot-product                              "dot product")
      (táirgeadh-tras                                cross-product                            "cross product")
      (teorainn                                      limit                                    "limit (calculus)")
      (D                                             D                                        "differential operator")
      (páirt-difreáil                                partial                                  "partial derivative")
      (comhartha                                     sign                                     "sign of number")
      (slánuimhir-randamach                          random-integer                           "random integer")
      (fíoruimhir-randamach                          random-real                              "random real number")
      (staitisticí-aisteora                          actor-stats                              "actor statistics")
      (aitheantas-aisteora                           actor-id                                 "actor identifier")
      (neamhshonraithe?                              unspecified?                             "is unspecified?")
      (suas                                          up                                       "up-tuple (contravariant)")
      (síos                                          down                                     "down-tuple (covariant)")
      (suas?                                         up?                                      "is up-tuple?")
      (síos?                                         down?                                    "is down-tuple?")
      (toipla?                                       tuple?                                   "is tuple?")
      (tagairt                                       ref                                      "reference/access")
      (toise                                         dimension                                "dimension")
      ))))

;; To activate: (set-active-language! "irish")
