;;; langs/latin.scm — Latina Classica (Classical Latin) language pack for Curry Scheme.
;;;
;;; Classical Latin language pack for Curry Scheme.
;;; 
;;; Latin is the direct source of much computing terminology. This pack
;;; reveals that connection: many Curry built-ins ARE already Latin words,
;;; or direct Latin derivatives. Programming in Latin makes the etymology
;;; visible.
;;; 
;;; Direct Latin sources in computing:
;;;   integer (whole, untouched) — integer IS Latin
;;;   vector (carrier) — vector IS Latin  
;;;   modulus (small measure) — source of 'module', 'modulo'
;;;   error (wandering) — error IS Latin
;;;   quotiens (how many times) — source of 'quotient'
;;;   sinus (fold/bay of a robe) — how trigonometry got its name
;;;   quantum (how much) — quantum IS Latin
;;;   momentum (movement, importance) — momentum IS Latin
;;;   limes (boundary) — source of 'limit'
;;;   radix (root) — source of 'radical'
;;;   gradus (step) — source of 'grade', 'degree'
;;; 
;;; The pack uses Classical Republican/Augustan Latin forms throughout.
;;;
;;; Usage:
;;;   (import (curry lang))
;;;   (lang:load-file! "langs/latin.scm")
;;;   ; or after installing: (lang:install! "latin")

(import (curry lang))

(register-language!
  `((id           . "latin")
    (display-name . "Latina Classica (Classical Latin)")
    (intro        . "Salve! Lingua Latina nunc activa est.")
    (error-preamble . "Error magnus:")
    (mappings     .
      ;; (foreign-name  canonical-name  "cultural/conceptual note")
      ((definio                                       define                                   "definio — I define, determine")
      (facio                                         lambda                                   "facio — I make, do (source of 'factory')")
      (si                                            if                                       "si — if")
      (incipio                                       begin                                    "incipio — I begin (source of 'inception')")
      (pono                                          set!                                     "pono — I place, set (source of 'position')")
      (esto                                          let                                      "esto — let it be (present imperative of esse)")
      (esto-deinceps                                 let*                                     "let it be in sequence")
      (esto-mutuo                                    letrec                                   "let it be mutually")
      (esto-mutuo-deinceps                           letrec*                                  "sequential mutual binding")
      (dico                                          quote                                    "dico — I say, speak (source of 'diction')")
      (quasi-dico                                    quasiquote                               "quasi — as if, almost")
      (solvo                                         unquote                                  "solvo — I loose, release (source of 'solve')")
      (solvo-spargo                                  unquote-splicing                         "loose and scatter")
      (et                                            and                                      "et — and (the most common Latin word)")
      (vel                                           or                                       "vel — or (for alternatives)")
      (quum                                          cond                                     "quum — when, since (classical conditional)")
      (casus                                         case                                     "casus — case, fall (source of 'case')")
      (quando                                        when                                     "quando — when")
      (nisi                                          unless                                   "nisi — unless, if not")
      (ago                                           do                                       "ago — I do, act, drive (source of 'agent')")
      (definio-syntaxin                              define-syntax                            "define syntax")
      (regulae-syntacticae                           syntax-rules                             "rules of syntax (regula = rule)")
      (definio-valores                               define-values                            "define multiple values")
      (definio-genus-tabulae                         define-record-type                       "define a record type")
      (valores                                       values                                   "valores — values (from valere, to be worth)")
      (voco-continuationem                           call/cc                                  "call the continuation")
      (voco-continuationem-praesentem                call-with-current-continuation           "call with current continuation")
      (importo                                       import                                   "importo — I bring in, import")
      (exporto                                       export                                   "exporto — I carry out, export")
      (definio-bibliothecam                          define-library                           "define a library (bibliotheca = book-place)")
      (custodio                                      guard                                    "custodio — I guard, watch (source of 'custody')")
      (parametrizo                                   parameterize                             "set parameters")
      (includo                                       include                                  "includo — I include, enclose")
      (differo                                       delay                                    "differo — I postpone (source of 'differ')")
      (differo-vi                                    delay-force                              "postpone by force")
      (gigno                                         spawn                                    "gigno — I beget, create (source of 'genesis')")
      (mitto                                         send!                                    "mitto — I send (source of 'mission')")
      (accipio                                       receive                                  "accipio — I receive, accept")
      (ipse                                          self                                     "ipse — itself, very self (emphatic)")
      (iungo                                         cons                                     "iungo — I join (source of 'junction')")
      (caput                                         car                                      "caput — head (source of 'capital')")
      (cauda                                         cdr                                      "cauda — tail")
      (series                                        list                                     "series — series, sequence, row")
      (longitudo                                     length                                   "longitudo — length, longitude")
      (addo                                          append                                   "addo — I add to (source of 'addition')")
      (inverto                                       reverse                                  "inverto — I turn over (source of 'invert')")
      (peto-seriei                                   list-ref                                 "seek from series")
      (cauda-seriei                                  list-tail                                "tail of series")
      (applico                                       map                                      "applico — I apply (source of 'application')")
      (per-singula                                   for-each                                 "per — through; singula — each one")
      (cerno                                         filter                                   "cerno — I sift, separate (source of 'discern')")
      (plico-sinistrorsum                            fold-left                                "fold toward the left")
      (plico-dextrorsum                              fold-right                               "fold toward the right")
      (socio                                         assoc                                    "socio — I associate (source of 'society')")
      (socio-idem                                    assq                                     "associate by identity")
      (membrum                                       member                                   "membrum — member, limb")
      (facio-seriem                                  make-list                                "make a series/list")
      (non                                           not                                      "non — not")
      (booleanum-aequale?                            boolean=?                                "booleans equal?")
      (adhibeo                                       apply                                    "adhibeo — I apply, use (source of 'inhibit')")
      (error                                         error                                    "error — wandering, mistake (error IS Latin!)")
      (tollo                                         raise                                    "tollo — I raise, lift (source of 'tolerate')")
      (maximum                                       max                                      "maximum — greatest (neuter superlative)")
      (minimum                                       min                                      "minimum — smallest (neuter superlative)")
      (absolutum                                     abs                                      "absolutum — unbound, absolute (source of 'absolute'!)")
      (nihilum?                                      zero?                                    "nihilum — nothing, zero (source of 'nihilism')")
      (positivum?                                    positive?                                "positivum — placed, positive")
      (negativum?                                    negative?                                "negativum — denying, negative")
      (impar?                                        odd?                                     "impar — unequal, odd (source of 'impar')")
      (par?                                          even?                                    "par — equal, even (source of 'parity')")
      (pavimentum                                    floor                                    "pavimentum — floor, pavement")
      (lacunar                                       ceiling                                  "lacunar — panelled ceiling")
      (rotundo                                       round                                    "rotundo — I round, make circular")
      (trunco                                        truncate                                 "trunco — I cut off, truncate")
      (potestas                                      expt                                     "potestas — power, authority (source of 'potent')")
      (radix                                         sqrt                                     "radix — root (source of 'radical'!)")
      (quotiens                                      quotient                                 "quotiens — how many times (source of 'quotient'!)")
      (residuum                                      remainder                                "residuum — what remains (source of 'residue')")
      (modulus                                       modulo                                   "modulus — small measure (source of 'module'!)")
      (m-c-d                                         gcd                                      "maximus communis divisor")
      (m-c-m                                         lcm                                      "minimum commune multiplum")
      (quadratum                                     square                                   "quadratum — square (source of 'quadrate')")
      (integer-exactum?                              exact-integer?                           "exact integer?")
      (radix-integri                                 exact-integer-sqrt                       "integer square root")
      (exactum                                       exact                                    "exactum — exact (exactum IS Latin!)")
      (inexactum                                     inexact                                  "inexact, approximate")
      (numerus-ad-textum                             number->string                           "number to text")
      (textus-ad-numerum                             string->number                           "text to number")
      (quotiens-truncatus                            truncate-quotient                        "truncated quotient")
      (residuum-truncatum                            truncate-remainder                       "truncated remainder")
      (divisio-truncans                              truncate/                                "truncating division")
      (sinus                                         sin                                      "sinus — sinus IS Latin (fold/bay of a robe)")
      (cosinus                                       cos                                      "cosinus — cosine (also Latin)")
      (exponens                                      exp                                      "exponens — exponential (source of 'exponent')")
      (logarithmus                                   log                                      "logarithmus (Neo-Latin compound)")
      (arcus-tangens                                 atan                                     "arc tangent (arcus = bow/arc)")
      (numerus?                                      number?                                  "numerus — number")
      (textus?                                       string?                                  "textus — woven text (source of 'text'!)")
      (symbolum?                                     symbol?                                  "symbolum — symbol, token")
      (logicum?                                      boolean?                                 "logicum — of logic")
      (actio?                                        procedure?                               "actio — action, procedure")
      (vector?                                       vector?                                  "vector — carrier (vector IS Latin!)")
      (littera?                                      char?                                    "littera — letter, character")
      (porta?                                        port?                                    "porta — door, gate (source of 'portal')")
      (exactum?                                      exact?                                   "exact?")
      (inexactum?                                    inexact?                                 "inexact?")
      (integer?                                      integer?                                 "integer — whole, untouched (integer IS Latin!)")
      (rationalis?                                   rational?                                "rationalis — rational (source of 'rational'!)")
      (reale?                                        real?                                    "reale — real (source of 'real'!)")
      (compositum?                                   complex?                                 "compositum — put together, complex")
      (par?                                          pair?                                    "par — a pair (cf. parity)")
      (nullum?                                       null?                                    "nullum — none, null (null IS Latin!)")
      (series?                                       list?                                    "series — is it a series?")
      (idem?                                         eq?                                      "idem — the same thing")
      (aequivalens?                                  eqv?                                     "aequivalens — of equal value")
      (aequale?                                      equal?                                   "aequale — equal (source of 'equal'!)")
      (ostendo                                       display                                  "ostendo — I show, display (source of 'ostentation')")
      (scribo                                        write                                    "scribo — I write (source of 'scribe')")
      (nova-linea                                    newline                                  "nova linea — new line")
      (lego                                          read                                     "lego — I read, collect (source of 'lecture')")
      (lego-lineam                                   read-line                                "read a line")
      (lego-litteram                                 read-char                                "read a character")
      (scribo-litteram                               write-char                               "write a character")
      (scribo-textum                                 write-string                             "write text")
      (aperio-tabulam-ingressus                      open-input-file                          "open file for entry")
      (aperio-tabulam-egressus                       open-output-file                         "open file for exit")
      (claudo-portam                                 close-port                               "claudo — close (source of 'close')")
      (proruo-portam                                 flush-output-port                        "flush output")
      (finis-tabulae?                                eof-object?                              "end of table/file?")
      (littera-parata?                               char-ready?                              "character ready?")
      (octo-parata?                                  u8-ready?                                "byte ready?")
      (lego-octo                                     read-u8                                  "read byte")
      (prospicio-octo                                peek-u8                                  "peek at byte")
      (lego-textum                                   read-string                              "read text")
      (lego-vectorem                                 read-bytevector                          "read bytevector")
      (lego-in-vectorem                              read-bytevector!                         "read into bytevector")
      (scribo-octo                                   write-u8                                 "write byte")
      (scribo-vectorem                               write-bytevector                         "write bytevector")
      (scribo-simpliciter                            write-simple                             "write simply")
      (tabula-adest?                                 file-exists?                             "tabula — tablet, file")
      (deleo-tabulam                                 delete-file                              "deleo — I delete, destroy")
      (voco-cum-tabula-ingressus                     call-with-input-file                     "call with input file")
      (voco-cum-tabula-egressus                      call-with-output-file                    "call with output file")
      (ingressus-a-tabula                            with-input-from-file                     "with input from file")
      (egressus-ad-tabulam                           with-output-to-file                      "with output to file")
      (error-lectionis?                              read-error?                              "reading error?")
      (error-tabulae?                                file-error?                              "file error?")
      (nuntium-erroris                               error-object-message                     "message of the error")
      (peto-variabilem-ambitus                       get-environment-variable                 "get environment variable")
      (peto-variabiles-ambitus                       get-environment-variables                "get all environment variables")
      (fugio-celeriter                               emergency-exit                           "fugio — I flee quickly")
      (secundum-praesens                             current-second                           "current second (secundus = following)")
      (momentum-praesens                             current-jiffy                            "current moment (momentum IS Latin!)")
      (momenta-per-secundum                          jiffies-per-second                       "moments per second")
      (facio-textum                                  make-string                              "make text")
      (textus                                        string                                   "textus — woven fabric, text")
      (longitudo-textus                              string-length                            "length of text")
      (peto-litteram                                 string-ref                               "seek a character")
      (addo-textum                                   string-append                            "add text")
      (describo                                      string-copy                              "describo — I copy, transcribe")
      (pars-textus                                   substring                                "part of text")
      (textus-ad-seriem                              string->list                             "text to series")
      (series-ad-textum                              list->string                             "series to text")
      (textus-maiusculis                             string-upcase                            "text in capitals")
      (textus-minusculis                             string-downcase                          "text in small letters")
      (textus-aequalis?                              string=?                                 "texts equal?")
      (textus-minor?                                 string<?                                 "text less than?")
      (textus-minor-aut-aequalis?                    string<=?                                "text ≤?")
      (textus-maior?                                 string>?                                 "text greater?")
      (textus-maior-aut-aequalis?                    string>=?                                "text ≥?")
      (textus-aequalis-sine-casu?                    string-ci=?                              "text = case-insensitive?")
      (textus-minor-sine-casu?                       string-ci<?                              "text < case-insensitive?")
      (textus-maior-sine-casu?                       string-ci>?                              "text > case-insensitive?")
      (textus-minor-aut-aequalis-sine-casu?          string-ci<=?                             "text ≤ case-insensitive?")
      (textus-maior-aut-aequalis-sine-casu?          string-ci>=?                             "text ≥ case-insensitive?")
      (textus-ad-symbolum                            string->symbol                           "text to symbol")
      (symbolum-ad-textum                            symbol->string                           "symbol to text")
      (pono-litteram-textu                           string-set!                              "set character in text")
      (describo-in                                   string-copy!                             "copy text into")
      (per-singulas-litteras                         string-for-each                          "for each character")
      (impleo-textum                                 string-fill!                             "fill text")
      (textus-casus-unus                             string-foldcase                          "fold text case")
      (textus-ad-utf8                                string->utf8                             "text to UTF-8")
      (utf8-ad-textum                                utf8->string                             "UTF-8 to text")
      (littera-ad-numerum                            char->integer                            "character to number")
      (numerus-ad-litteram                           integer->char                            "number to character")
      (litterae-aequales?                            char=?                                   "characters equal?")
      (littera-minor?                                char<?                                   "character less than?")
      (littera-minor-aut-aequalis?                   char<=?                                  "char ≤?")
      (littera-maior?                                char>?                                   "character greater?")
      (littera-maior-aut-aequalis?                   char>=?                                  "char ≥?")
      (litterae-aequales-sine-casu?                  char-ci=?                                "char = case-insensitive?")
      (littera-minor-sine-casu?                      char-ci<?                                "char < case-insensitive?")
      (littera-maior-sine-casu?                      char-ci>?                                "char > case-insensitive?")
      (littera-minor-aut-aequalis-sine-casu?         char-ci<=?                               "char ≤ case-insensitive?")
      (littera-maior-aut-aequalis-sine-casu?         char-ci>=?                               "char ≥ case-insensitive?")
      (valor-digiti                                  digit-value                              "value of digit character")
      (littera-casus-unus                            char-foldcase                            "fold character case")
      (facio-vectorem                                make-vector                              "make a vector")
      (vector                                        vector                                   "vector — carrier (vector IS Latin!)")
      (longitudo-vectoris                            vector-length                            "length of vector")
      (peto-vectoris                                 vector-ref                               "seek element of vector")
      (pono-vectorem                                 vector-set!                              "set element of vector")
      (vector-ad-seriem                              vector->list                             "vector to series")
      (series-ad-vectorem                            list->vector                             "series to vector")
      (impleo-vectorem                               vector-fill!                             "fill vector")
      (describo-vectorem                             vector-copy                              "copy vector")
      (applico-vectorem                              vector-map                               "map over vector")
      (per-singula-vectoris                          vector-for-each                          "for each in vector")
      (addo-vectorem                                 vector-append                            "append vectors")
      (describo-in-vectorem                          vector-copy!                             "copy into vector")
      (facio-vectorem-octorum                        make-bytevector                          "make byte vector")
      (vector-octorum                                bytevector                               "vector of bytes")
      (longitudo-vectoris-octorum                    bytevector-length                        "length of byte vector")
      (peto-octum                                    bytevector-u8-ref                        "get byte")
      (pono-octum                                    bytevector-u8-set!                       "set byte")
      (describo-vectorem-octorum                     bytevector-copy                          "copy byte vector")
      (describo-in-vectorem-octorum                  bytevector-copy!                         "copy into byte vector")
      (addo-vectorem-octorum                         bytevector-append                        "append byte vectors")
      (variabilis-symbolica                          sym-var                                  "symbolic variable")
      (variabilis-symbolica?                         sym-var?                                 "is symbolic variable?")
      (expressio-symbolica?                          sym-expr?                                "is symbolic expression?")
      (symbolicum?                                   symbolic?                                "is symbolic?")
      (nomen-variabilis                              sym-var-name                             "name of variable")
      (suppositio-variabilis?                        sym-assumption?                          "has assumption?")
      (differentiatio-symbolica                      sym-diff                                 "symbolic differentiation (differentiatio = distinction)")
      (differentiatio-fractalis                      frac-diff                                "fractional differentiation")
      (Wirtinger-d                                   wirtinger-d                              "Wirtinger derivative")
      (Wirtinger-d-coniugatum                        wirtinger-dbar                           "Wirtinger conjugate derivative")
      (differentiatio-automatica                     auto-diff                                "automatic differentiation")
      (integro                                       integrate                                "integro — I integrate (integro IS Latin: make whole!)")
      (integratio-fractalis                          frac-int                                 "fractional integration")
      (simplifico                                    simplify                                 "simplifico — I make simple (source of 'simplify'!)")
      (substituo                                     substitute                               "substituo — I put in place of (source of 'substitute'!)")
      (expando                                       expand                                   "expando — I spread out (source of 'expand'!)")
      (gradus                                        degree                                   "gradus — step, degree (source of 'grade'!)")
      (colligo                                       collect                                  "colligo — I collect (source of 'collect'!)")
      (coefficiens-primum                            leading-coeff                            "leading coefficient")
      (coniugo                                       conjugate                                "coniugo — I yoke together (source of 'conjugate'!)")
      (coniugo                                       conj                                     "conjugate (short)")
      (symbolum-ad-textum                            sym->string                              "symbolic to text")
      (symbolum-ad-medium                            sym->infix                               "symbolic to infix")
      (symbolum-ad-formulas                          sym->latex                               "symbolic to LaTeX")
      (superreale?                                   surreal?                                 "superreale — super-real")
      (superreale-infinitum?                         surreal-infinite?                        "surreal infinite?")
      (superreale-finitum?                           surreal-finite?                          "surreal finite?")
      (superreale-infinitesimum?                     surreal-infinitesimal?                   "surreal infinitesimal?")
      (pars-realis                                   surreal-real-part                        "real part")
      (pars-omega                                    surreal-omega-part                       "omega part")
      (pars-epsilon                                  surreal-epsilon-part                     "epsilon part")
      (dies-natalis                                  surreal-birthday                         "dies natalis — birthday (Roman term)")
      (numerus-terminorum                            surreal-nterms                           "number of terms")
      (superreale-ad-numerum                         surreal->number                          "surreal to number")
      (facio-superreale                              make-surreal                             "make surreal number")
      (termini-superrealis                           surreal-terms                            "terms of surreal")
      (superpono                                     superpose                                "superpono — I place upon, superpose")
      (quantum-aequabile                             quantum-uniform                          "uniform quantum (quantum IS Latin: 'how much'!)")
      (observo                                       observe                                  "observo — I observe (observo IS Latin!)")
      (quantum?                                      quantum?                                 "quantum — how much? (quantum IS Latin!)")
      (status-quanta                                 quantum-states                           "quantum states")
      (numerus-quanta                                quantum-n                                "number of quantum branches")
      (facio-multivectorem                           make-mv                                  "make multivector")
      (multivector?                                  mv?                                      "is multivector?")
      (signatura-multivectoris                       mv-signature                             "Clifford signature")
      (peto-multivectoris                            mv-ref                                   "multivector blade ref")
      (pono-multivectorem                            mv-set!                                  "set multivector component")
      (multivector+                                  mv+                                      "multivector addition")
      (multivector-                                  mv-                                      "multivector subtraction")
      (multivector*                                  mv*                                      "geometric product")
      (scala-multivectori                            mv-scale                                 "scale multivector")
      (cuneus-multivectoris                          mv-wedge                                 "wedge product (cuneus = wedge)")
      (contractio-sinistra                           mv-lcontract                             "left contraction")
      (inverto-multivectorem                         mv-reverse                               "reverse multivector")
      (involvo-multivectorem                         mv-involute                              "involute")
      (coniugatum-multivectoris                      mv-conjugate                             "Clifford conjugate")
      (duplex-multivectoris                          mv-dual                                  "dual multivector")
      (gradus-multivectoris                          mv-grade                                 "grade projection")
      (scalare-multivectoris                         mv-scalar                                "scalar part")
      (norma-quadrata-multivectoris                  mv-norm2                                 "squared norm")
      (norma-multivectoris                           mv-norm                                  "norm")
      (normalizo-multivectorem                       mv-normalize                             "normalize")
      (elementum-multivectoris                       mv-e                                     "basis blade")
      (multivector-ex-serie                          mv-from-list                             "multivector from list")
      (quaternio-ad-multivectorem                    quaternion->mv                           "quaternion to multivector")
      (multivector-ad-quaternionem                   mv->quaternion                           "multivector to quaternion")
      (facio-quaternionem                            make-quaternion                          "quaternio — quaternion (group of four, Roman unit!)")
      (quaternio?                                    quaternion?                              "is quaternion?")
      (facio-octavum                                 make-octonion                            "octonion (group of eight)")
      (octavum?                                      octonion?                                "is octonion?")
      (peto-octavum                                  octonion-ref                             "octonion component")
      (histrio-vivit?                                actor-alive?                             "histrio — actor, theatrical player")
      (rationalis-ad-sexagesimam                     rational->sexagesimal                    "rational to Babylonian base-60")
      (sexagesima-ad-rationalem                      sexagesimal->rational                    "sexagesimal to rational")
      (hms-ad-secunda                                hms->seconds                             "hours-minutes-seconds to seconds")
      (secunda-ad-hms                                seconds->hms                             "seconds to HMS")
      (dms-ad-gradus                                 dms->degrees                             "degrees-minutes-seconds to decimal")
      (gradus-ad-dms                                 degrees->dms                             "decimal to DMS")
      (notatio-praesens                              current-number-notation                  "current number notation")
      (facio-variabilem-transactionis                make-tvar                                "make transactional variable")
      (lego-variabilem-transactionis                 tvar-read                                "read tvar")
      (scribo-variabilem-transactionis               tvar-write!                              "write tvar")
      (atomice                                       atomically                               "atomice — atomically (atomus = indivisible, from Greek!)")
      (concurrentia-ferramentorum                    hardware-concurrency                     "hardware thread count")
      (per-singula-pariter                           for-each/par                             "parallel for-each")
      (reduco                                        reduce                                   "reduco — I lead back, reduce")
      (gradiens                                      grad                                     "gradiens — going, gradient")
      (divergentia                                   divergence                               "divergentia — divergence")
      (rotor                                         curl                                     "rotor — rotator")
      (Laplacianus                                   laplacian                                "Laplacian operator")
      (productum-puncti                              dot-product                              "dot product")
      (productum-crucis                              cross-product                            "cross product")
      (limes                                         limit                                    "limes — boundary, limit")
      (D                                             D                                        "differential operator")
      (derivatio-partialis                           partial                                  "partial derivative")
      (signum                                        sign                                     "signum — sign, mark (source of 'sign'!)")
      (integer-fortuitus                             random-integer                           "random integer")
      (reale-fortuitum                               random-real                              "random real number")
      (status-histrionis                             actor-stats                              "actor statistics")
      (identitas-histrionis                          actor-id                                 "actor identifier")
      (indeterminatum?                               unspecified?                             "unspecified?")
      (sursum                                        up                                       "sursum — upward")
      (deorsum                                       down                                     "deorsum — downward")
      (sursum?                                       up?                                      "is up-tuple?")
      (deorsum?                                      down?                                    "is down-tuple?")
      (nexum?                                        tuple?                                   "nexum — tied together, tuple")
      (peto                                          ref                                      "peto — I seek, request")
      (dimensio                                      dimension                                "dimensio — measuring out, dimension")
      ))))

;; To activate: (set-active-language! "latin")
