" Vim syntax file
" Language:    Curry Scheme
" Maintainer:  generated by tools/gen-editor-syntax.py — do not edit

if exists("b:current_syntax")
  finish
endif

" R7RS identifier characters (excludes , ; ' ` ")
syn iskeyword 33,36-38,42-43,45-58,60-64,65-90,94-95,97-122,126

" ---- comments -------------------------------------------------
syn match   curryComment /;.*$/ contains=@Spell
syn match   curryComment /#!.*$/
syn region  curryBlockComment start=/#|/ end=/|#/ contains=curryBlockComment
syn match   curryDatumComment /#;/

" ---- strings and characters -----------------------------------
syn region  curryString start=/"/ skip=/\\\\\|\\"/ end=/"/ contains=curryStringEscape
syn match   curryStringEscape /\\\%([abntr\\"]\|x\x\+;\?\)/ contained
syn match   curryChar /#\\\%(x\x\+\|alarm\|backspace\|delete\|escape\|newline\|null\|return\|space\|tab\|.\)/

" ---- booleans, keyword objects, quoting -----------------------
syn match   curryBoolean /#\%(true\|false\|t\|f\)\%([[:space:]()\[\]\x27`",;]\|$\)\@=/
syn match   curryKeywordObj /#:[^[:space:]()\[\]\x27`",;]\+/
syn match   curryQuote /['`]\|,@\?/

" ---- numbers ---------------------------------------------------
syn match   curryNumber /\%(^\|[[:space:]()\[\]\x27`",;]\)\@<=[-+]\?\d\+\%(\/\d\+\|\.\d*\%([eE][-+]\?\d\+\)\?\)\?\%([[:space:]()\[\]\x27`",;]\|$\)\@=/
syn match   curryRadixNumber /#[bodxBODX][-+]\?[0-9a-fA-F]\+\%(\/[0-9a-fA-F]\+\)\?/
" Neugebauer sexagesimal: #s1;30 = 3/2, #s1,0,0 = 3600
syn match   currySexagesimal /#[sS]\d\+\%(,\d\+\)*\%(;\d\+\%(,\d\+\)*\)\?/
" Cuneiform numerals 𒁹=1 𒌋=10 𒑊=0.  The reader merges single-space-
" separated glyph groups into ONE token, then checks the synonym table,
" then parses as a sexagesimal number.  So a lone group defers to a
" synonym (𒁹 is `define`, 𒁹𒁹𒁹 is `newline`) but a spaced multi-group
" run is always a number (𒁹 𒌋𒁹 = 71).  Vim priority is definition
" order (later wins at the same position): single-group number here,
" synonyms after it, multi-group number last.
syn match   curryCuneiformNumber /\%(^\|[[:space:]()\[\]\x27`",;]\)\@<=[𒁹𒌋𒑊]\+\%([[:space:]()\[\]\x27`",;]\|$\)\@=/

" ---- special forms ---------------------------------------------
syn keyword curryForm ... => and begin case cond cond-expand define define-algebra define-library define-record-type define-rule
syn keyword curryForm define-ruleset define-syntax define-values defined? delay delay-force do else except export fields file-error
syn keyword curryForm for guard if immutable import include lambda let let* let*-values let-syntax let-values
syn keyword curryForm letrec letrec* letrec-syntax library link! monitor! mutable only or parameterize prefix quasiquote
syn keyword curryForm quote read-error rename set! symbolic syntax-rules unless unquote unquote-splicing when with-assumptions
syn match curryForm /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(→\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/

" ---- builtin procedures ----------------------------------------
syn keyword curryBuiltin %channel-blocked? %channel-try-recv %channel-try-send %condition-type-register! %find-restart %handler-bind-1 %invoke-restart %make-condition %make-restart %or-else %record-ctor %record-pred?
syn keyword curryBuiltin %record-ref %record-set! %signal %with-restarts * + - / < <= = >
syn keyword curryBuiltin >= D abs abundant? acos acosh actor-alive? actor-id actor-set-name! actor-stats actor? angle
syn keyword curryBuiltin append apply arithmetic-shift asin asinh assoc assoc-laguerre assoc-legendre assq assume! assv atan
syn keyword curryBuiltin atanh atomically auto-diff bell bernoulli bessel-i bessel-j bessel-k bessel-y best-rational-approx beta big-omega
syn keyword curryBuiltin binomial bitwise-and bitwise-not bitwise-or bitwise-xor boolean=? boolean? breakpoint bytevector bytevector-append bytevector-copy bytevector-copy!
syn keyword curryBuiltin bytevector-length bytevector-u8-ref bytevector-u8-set! bytevector? caaar caadr caar cadar caddr cadr call-with-current-continuation call-with-input-file
syn keyword curryBuiltin call-with-output-file call-with-port call-with-precision call-with-values call/cc can-assume? car carmichael catalan cdaar cdadr cdar
syn keyword curryBuiltin cddar cdddr cddr cdr ceiling channel-close! channel-closed? channel-recv! channel-send! channel? char->integer char-alphabetic?
syn keyword curryBuiltin char-ci<=? char-ci<? char-ci=? char-ci>=? char-ci>? char-downcase char-foldcase char-lower-case? char-numeric? char-ready? char-upcase char-upper-case?
syn keyword curryBuiltin char-whitespace? char<=? char<? char=? char>=? char>? char? chebyshev-t chebyshev-u chinese-remainder clear-rules! close-input-port
syn keyword curryBuiltin close-output-port close-port collect complex? condition-backtrace condition-code condition-field condition-fields condition-is-a? condition-message condition-type condition?
syn keyword curryBuiltin conj conjugate cons continued-fraction convergents cos cosh cot cross-product csc curl current-error-port
syn keyword curryBuiltin current-input-port current-jiffy current-number-notation current-output-port current-precision current-second curry-jit-call curry-jit-eval curry-llvm-available? curry-llvm-dump-last deficient? degree
syn keyword curryBuiltin delete-file denominator digamma digit-value dimension divergence divisor-count divisor-sum divisors dot-product down down?
syn keyword curryBuiltin drop-assumption! dynamic-wind elliptic-e elliptic-f elliptic-k elliptic-pi emergency-exit eof-object eof-object? eq? equal? eqv?
syn keyword curryBuiltin erf erfc error error-message error-object->string error-object-code error-object-irritants error-object-message error-object? euler-number eval even?
syn keyword curryBuiltin exact exact->inexact exact-integer-sqrt exact-integer? exact? exit exp expand expt extended-gcd factor fibonacci
syn keyword curryBuiltin file-error? file-exists? filter finite? floor floor-quotient floor-remainder floor/ flush-output-port fn-apply fold-left fold-right
syn keyword curryBuiltin for-each for-each/par force fourier frac-diff frac-int gamma gc gc-collect! gc-enable-incremental! gc-free-bytes gc-heap-size
syn keyword curryBuiltin gc-mode gc-on-collection gc-set-free-space-divisor! gc-set-max-heap! gc-stats gc-stats-reset! gc-total-bytes gcd gensym get-environment-variable get-environment-variables get-output-bytevector
syn keyword curryBuiltin get-output-string grad gradient groebner hardware-concurrency hash-table->alist hash-table-delete! hash-table-exists? hash-table-keys hash-table-ref hash-table-set! hash-table-size
syn keyword curryBuiltin hash-table-values hash-table? hermite hermite-prob ifourier ilaplace imag-part inexact inexact->exact inexact? infinite? input-port-open?
syn keyword curryBuiltin input-port? integer->char integer? integrate interaction-environment interval interval-contains? interval-hi interval-lo interval-midpoint interval-width interval?
syn keyword curryBuiltin jacobi-symbol jiffies-per-second jit-call-depth jit-compile! kronecker-symbol laguerre laplace laplacian laurent lcm leading-coeff legendre
syn keyword curryBuiltin legendre-symbol length limit list list* list->down list->set list->string list->up list->vector list-copy list-head
syn keyword curryBuiltin list-ref list-rules list-tail list? load log log-gamma lucas magnitude make-bytevector make-channel make-hash-table
syn keyword curryBuiltin make-interval make-list make-octonion make-parameter make-polar make-promise make-quaternion make-random-source make-rectangular make-set make-string make-surreal
syn keyword curryBuiltin make-tvar make-vector map map-parallel-threshold map/seq max member memq memv min mobius mod-expt
syn keyword curryBuiltin mod-inverse modulo mpfr mpfr-apery mpfr-catalan mpfr-e mpfr-erf mpfr-erfc mpfr-euler mpfr-exp mpfr-fma mpfr-gamma
syn keyword curryBuiltin mpfr-hypot mpfr-j0 mpfr-j1 mpfr-lgamma mpfr-log mpfr-log10 mpfr-log2 mpfr-log2-of mpfr-phi mpfr-pi mpfr-precision mpfr-rounding-mode
syn keyword curryBuiltin mpfr-set-precision mpfr-sqrt mpfr-zeta mpfr? multinomial nan? negative? newline next-prime not null? num-divisors
syn keyword curryBuiltin number->string number? numerator observe octonion-ref octonion? odd? omega open-input-bytevector open-input-file open-input-string open-output-bytevector
syn keyword curryBuiltin open-output-file open-output-string output-port-open? output-port? pair? partial partial-fractions partition-count peek-char peek-u8 perfect-power? perfect?
syn keyword curryBuiltin poly-factor poly-gcd poly-resultant poly-squarefree port? positive? prev-prime prime-factors prime? procedure? profiling-report profiling-reset
syn keyword curryBuiltin promise? puiseux quad quad-frac-diff quad-frac-int quantum-n quantum-states quantum-uniform quantum? quaternion* quaternion+ quaternion-conjugate
syn keyword curryBuiltin quaternion-inverse quaternion-norm quaternion-normalize quaternion-rotate-vector quaternion-w quaternion-x quaternion-y quaternion-z quaternion? quit quotient raise
syn keyword curryBuiltin raise-continuable random-integer random-real random-source->random-integer random-source->random-real random-source-pseudo-randomize! random-source-randomize! random-source? rational? read read-bytevector read-bytevector!
syn keyword curryBuiltin read-char read-error? read-line read-string read-u8 real-part real? receive reduce reduce/seq ref remainder
syn keyword curryBuiltin restart-description restart-name restart? retry reverse round sec self send! series set->list set-add!
syn keyword curryBuiltin set-adjoin set-adjoin! set-any? set-car! set-cdr! set-copy set-count set-delete set-delete! set-difference set-empty? set-every?
syn keyword curryBuiltin set-filter set-filter! set-find set-fold set-for-each set-intersection set-map set-map-parallel-threshold! set-member? set-size set-subset? set-symmetric-difference
syn keyword curryBuiltin set-union set=? set? sign simplify sin sinh smooth? solve solve-system spawn spherical-harmonic
syn keyword curryBuiltin sqrt square squarefree? stirling1 stirling2 string string->list string->number string->symbol string->utf8 string-append string-ci<=?
syn keyword curryBuiltin string-ci<? string-ci=? string-ci>=? string-ci>? string-contains string-copy string-copy! string-downcase string-fill! string-foldcase string-for-each string-length
syn keyword curryBuiltin string-ref string-set! string-upcase string<=? string<? string=? string>=? string>? string? substitute substring sum-divisors
syn keyword curryBuiltin superpose surreal->number surreal-birthday surreal-epsilon-part surreal-finite? surreal-infinite? surreal-infinitesimal? surreal-nterms surreal-omega-part surreal-real-part surreal-terms surreal?
syn keyword curryBuiltin sym->infix sym->latex sym->string sym-assumption? sym-diff sym-expr sym-expr-arg sym-expr-nargs sym-expr-op sym-expr? sym-fn sym-fn-name
syn keyword curryBuiltin sym-fn? sym-var sym-var-name sym-var? symbol->string symbol? symbolic? system tan tanh totient trace
syn keyword curryBuiltin traced? tree-eval trigsimp truncate truncate-quotient truncate-remainder truncate/ tuple->list tuple? tvar-read tvar-write! tvar?
syn keyword curryBuiltin u8-ready? unspecified? untrace up up? utf8->string values vec-laplacian vec3-project-batch vector vector->list vector-append
syn keyword curryBuiltin vector-copy vector-copy! vector-fill! vector-for-each vector-length vector-map vector-ref vector-set! vector? void wirtinger-d wirtinger-dbar
syn keyword curryBuiltin with-exception-handler with-input-from-file with-output-to-file with-output-to-string write write-bytevector write-char write-shared write-simple write-string write-u8 zero?
syn match curryBuiltin /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(display\|∂\|∫\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/

" ---- Akkadian / cuneiform synonyms -----------------------------
syn match curryAkkForm /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(šakānum-ṭupšarrim\|šakānum-nikkassī\|leqûm-tadārum-w\|pašārum-šapārum\|šakānum-ṣimtim\|leqûm-tadārum\|naṭālum-arkûm\|riksum-dannum\|leqûm-watrum\|šumma-ribûm\|ṭupšarrūtum\|kīma-libbi\|bīt-ṭuppi\|lā-inūma\|nikkassū\|ištartu\|maḫārum\|naṣārum\|pašārum\|wālādum\|šakānum\|šapārum\|alākum\|epēšum\|erēbum\|riksum\|šīmtum\|inūma\|leqûm\|qebûm\|waṣûm\|šanûm\|šumma\|kīma\|ana\|𒅁𒄀𒌋\|𒆠𒈠𒅁\|𒇲𒁹𒃲\|𒉡𒆠𒊕\|lū\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/
syn match curryAkkForm /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(𒀀𒈾\|𒁀𒀀\|𒁀𒌝\|𒁹𒆠\|𒁹𒈷\|𒁹𒋻\|𒁹𒌝\|𒂍𒌝\|𒂗𒉡\|𒅁𒀀\|𒅁𒄀\|𒅁𒌋\|𒆠𒂗\|𒆠𒈠\|𒇲𒁹\|𒈠𒄭\|𒉡𒆠\|𒉡𒌑\|𒋗𒈠\|𒌑𒀸\|𒌝𒌋\|u\|𒀸\|𒁹\|𒂗\|𒄿\|𒅁\|𒇻\|𒇽\|𒈷\|𒋗\|𒌋\|𒌑\|𒌝\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/
syn match curryAkkBuiltin /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(mithāriš-ṣeḫērum-mitḫārum-ṣibtim?\|mithāriš-ṣeḫērum-mitḫārum-ṭuppim?\|mithāriš-rabûm-mitḫārum-ṣibtim?\|mithāriš-rabûm-mitḫārum-ṭuppim?\|ṣeḫērum-ū-mitḫārum-ṣibtim?\|mithāriš-mitḫārum-ṣibtim?\|mithāriš-mitḫārum-ṭuppim?\|mithāriš-ṣeḫērum-ṣibtim?\|mithāriš-ṣeḫērum-ṭuppim?\|rabûm-ū-mitḫārum-ṣibtim?\|šemûm-ṭuppi-ṣibtātim-ina\|šutur-ṭuppi-ṣibtātim-ina\|ṣeḫērum-mitḫārum-ṭuppim?\|maḫārum-ṭuppi-ṣibtātim\|mithāriš-rabûm-ṣibtim?\|mithāriš-rabûm-ṭuppim?\|rabûm-mitḫārum-ṭuppim?\|ša-dāriš-ana-nikkassim\|šakānum-ṭuppi-ṣibtātim\|šaṭārum-ṭuppi-ṣibtātim\|epēšum-ṭuppi-ṣibtātim\|mīnum-ṭuppi-ṣibtātim\|naṭālum-ṣibtum-riqqi\|nikkassum-ana-ṣibtim\|redûm-ṭuppi-ṣibtātim\|šaṭārum-ṣibtum-riqqi\|šemûm-ṭuppi-ṣibtātim\|šutur-ṭuppi-ṣibtātim\|ṣibtum-ana-nikkassim\|ṣibtum-riqqi-maḫrum?\|ṣindānum-ana-nindabî\|ṭuppi-la-idûm-išārum\|ṭuppum-ana-nikkassim\|ibum-ṣīrum-kibrātim\|nikkassum-ana-ṭuppi\|nikkassum-ša-ṣibtim\|nindabûm-ana-ṣindim\|ṭuppi-ṣīrum-la-idûm\|ṭuppum-ana-ṣibtātim\|kibrātum-ana-rebîm\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/
syn match curryAkkBuiltin /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(kinattu-nikkassum?\|mitḫurtum-kibrātim\|nindabûm-ana-ṭuppi\|petûm-ṭuppi-erēbim\|rebûm-ana-kibrātim\|šemûm-ṣibtum-riqqi\|šutakūlum-kibrātim\|ṣibtātum-ana-ṭuppi\|ṭuppum-ana-nindabî\|ana-kālāma-ṣindim\|ana-kālāma-ṭuppim\|ana-ṭuppi-šaṭārum\|napḫarum-kibrātim\|nindabûm-ša-dāriš\|petûm-ṭuppi-waṣîm\|šaṭārum-ina-ṭuppi\|šutakūlum-nindabî\|ṣilippum-kibrātim\|ṭuppum-maḫārum-eq\|kibrātim-maḫārum\|matāḫum-kibrātim\|maḫārum-kibrātim\|mitḫārum-ṣibtim?\|mitḫārum-ṭuppim?\|nakārum-kibrātim\|nikkassum-šalim?\|nindabûm-maḫārum\|šakānum-kibrātim\|šinīpat-kibrātim\|šutakūlum-ṣindim\|šutur-ṣindim-ina\|ūmum-ēṭum-inanna\|ḫarāṣum-kibrātim\|ṣeḫērum-mitḫārum\|ṭuppum-ana-šumim\|epēšum-kibrātim\|epēšum-nindabîm\|epēšum-ša-dāriš\|ina-ṭuppi-šemûm\|kalāma-mitḫārum\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/
syn match curryAkkBuiltin /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(kalāma-nindabûm\|lapātum-imittam\|lapātum-šumēlam\|maḫārum-samānûm\|mitḫārum-kēnim?\|mitḫārum-šalim?\|nindabûm-zibbat\|nindabûm-šupur?\|turrum-kibrātim\|šemûm-ina-ṭuppi\|šumum-ana-ṭuppi\|ṣeḫērum-ṣibtim?\|ṣeḫērum-ṭuppim?\|ṣibtum-mithāriš\|ṣifrum-kibrātim\|ṣimdat-kibrātim\|ṣimdat-la-idûm?\|ṭarādū-ina-ūmim\|ṭuppum-mithāriš\|ṭuppum-ṣibtātim\|ašarēdum-ṣīrum\|epēšum-samānûm\|katābum-ṭuppim\|la-idûm-šalim?\|libbum-maḫārum\|maḫārum-ṣindim\|maḫārum-ṭuppim\|māḫirum-išārum\|māḫirum-ramāni\|mīnum-ša-dāriš\|napḫarum-ṣīrum\|pānum-kibrātim\|rabûm-mitḫārum\|rēšum-nikkassī\|tawirtum-ṣīrum\|zâzum-kibrātim\|ša-dāriš-kīnum\|šakānum-ṣindim\|šakānum-ṭuppim\|šanûm-kibrātim\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/
syn match curryAkkBuiltin /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(šaṭārum-ṣibtum\|šaṭārum-ṭuppam\|ḫarāṣum-warkûm\|ḫiṭītum-šemûm?\|ḫiṭītum-ṭuppi?\|ṣibtum-maḫrum?\|ṣibûm-kibrātim\|ṣīrum-ša-dāriš\|ṭarādum-inanna\|ṭuppum-ibašši?\|ṭuppum-maḫārum\|awât-la-idûm?\|epēšum-ṣindum\|epēšum-ṭuppam\|ibum-kibrātim\|libbum-ṭuppim\|mitḫārum-eqv?\|māḫirum-ḫepûm\|naṭālum-ṣīrum\|pašārum-bābim\|qātum-ḫarāṣim\|rabûm-ṣibtim?\|rabûm-ṭuppim?\|šapaltu-ippeš\|šapaltu-ṣīrum\|šaplûm-ṭuppim\|šaṭārum-ṣīrum\|šērum-ḫarāṣim\|ṣiḫrum-ṣīrum?\|ṭuppi-la-idûm\|awāt-ḫiṭītim\|epēšum-rebûm\|ibum-kinattu\|malûm-ṣindim\|malûm-ṭuppim\|mitḫārum-eq?\|mīnum-kalāma\|mīnum-ṣindim\|mīnum-ṭuppim\|redûm-ṣindim\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/
syn match curryAkkBuiltin /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(redûm-ṭuppim\|šemûm-ṣibtum\|šemûm-ṭuppam\|šutur-ṣindim\|šutur-ṭuppim\|ḫarāṣum-kala\|awātāt-bīti\|aṣûm-dannum\|elûm-ṭuppim\|eqlum-ḫepûm\|lā-kinattu?\|šemûm-ašrum\|šum-la-idûm\|ūm-wulludim\|ḫepûm-ṭuppi\|ana-kālāma\|elûm-ṣīrum\|lā-kinattu\|māḫirum-la\|nikkassum?\|ṭupšarrum?\|awāt-bīti\|kibrātim?\|la-dāriš?\|mitḫartum\|nindabûm?\|ša-dāriš?\|ša-ṣiḫrim\|šutakūlum\|ašarēdum\|balāṭum?\|kinattu?\|kippatum\|la-idûm?\|mitḫārum\|napḫarum\|nindabûm\|nukkurum\|pārisum?\|samānûm?\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/
syn match curryAkkBuiltin /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(tawirtum\|zibbatum\|šuklulum\|ṣindānum\|damqum?\|išārum?\|kalāma?\|kinattu\|la-idûm\|labārum\|lemnûm?\|matāḫum\|māḫirum\|naṭālum\|paqādum\|pirištu\|qitnūm?\|rakāsum\|rapāšum\|sakārum\|šaṭārum\|ḫarāṣum\|ḫiṭītum\|ṣeḫērum\|ṣibtum?\|ṣifrum?\|amārum\|bābum?\|dāriš?\|kabrum\|kalāma\|kēnum?\|kīttum\|qallum\|qātum?\|ramānī\|rebûm?\|turrum\|zûzum?\|šaplûm\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/
syn match curryAkkBuiltin /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(šinûm?\|šumum?\|šūnum?\|ḫepûm?\|ṣiḫrum\|ṣīrum?\|ṭuppum\|𒁀𒈠𒉡𒃲𒁹?\|eqlum\|kânum\|mīnum\|našûm\|qātum\|rabûm\|redûm\|rēšum\|zâzum\|šemûm\|šērum\|ṣêrum\|𒁀𒈠𒃲𒁹?\|𒁀𒈠𒉡𒃲?\|𒁀𒉡𒃲𒁹?\|𒈠𒌝𒃲𒁹?\|𒈠𒌝𒉡𒁹?\|elûm\|ibum\|𒁀𒃲𒁹?\|𒁀𒈠𒃲?\|𒁀𒈠𒈠?\|𒁀𒉡𒃲?\|𒅁𒈷𒈷?\|𒅆𒌝𒁀𒁹\|𒆠𒃲𒁀𒀀\|𒆠𒃲𒂗𒉡\|𒆠𒃲𒄀𒁹\|𒆠𒃲𒅁𒁹\|𒆠𒃲𒅁𒌑\|𒆠𒃲𒇲𒌑\|𒆠𒃲𒈠𒋻\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/
syn match curryAkkBuiltin /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(𒆠𒃲𒈧𒁹\|𒆠𒃲𒈷𒈷\|𒆠𒃲𒉡𒄿\|𒆠𒃲𒉡𒉡\|𒆠𒃲𒋻𒁹\|𒈠𒌝𒃲?\|𒈠𒌝𒈠?\|𒈠𒌝𒉡?\|𒉡𒅆𒁹?\|𒉡𒅆𒌝𒁹\|𒉡𒅆𒌝𒌋\|𒉡𒉡𒀀?\|𒋻𒉡𒅆?\|𒌝𒁀𒁹𒁹\|𒌝𒁀𒄿𒁹\|𒌝𒃲𒁹?\|𒌝𒉡𒁹?\|𒀀𒈾𒆠\|𒀭𒀭?\|𒀭𒀭𒁹\|𒀭𒁹?\|𒀭𒆠𒈠\|𒀸𒁹𒁹\|𒀸𒄿𒁹\|𒀸𒌋𒁹\|𒁀𒃲?\|𒁀𒈠?\|𒁀𒋻𒁹\|𒁹𒀸𒀸\|𒁹𒀸𒁹\|𒁹𒁹𒀸\|𒁹𒁹𒁹\|𒁹𒆠𒁹\|𒁹𒌝?\|𒂍𒀸?\|𒂍𒅆𒁹\|𒂍𒈷𒈷\|𒂍𒌝𒁹\|𒂗𒂗?\|𒃲𒁹𒁹\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/
syn match curryAkkBuiltin /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(𒃲𒁹𒌋\|𒄷𒂍?\|𒄷𒅆?\|𒅁𒃲?\|𒅁𒆠𒁹\|𒅁𒈷?\|𒅁𒈷𒈷\|𒅁𒈷𒊕\|𒅆𒁀?\|𒅆𒁀𒁹\|𒅆𒁹?\|𒅆𒉡𒁹\|𒅆𒋻𒁹\|𒅆𒌝𒁀\|𒆠𒀸?\|𒆠𒁹𒁹\|𒆠𒃲?\|𒆠𒃲𒀸\|𒆠𒃲𒁹\|𒆠𒃲𒂗\|𒆠𒃲𒅁\|𒆠𒃲𒅆\|𒆠𒃲𒇽\|𒆠𒃲𒈧\|𒆠𒃲𒊕\|𒆠𒃲𒋻\|𒆠𒃲𒌋\|𒆠𒃲𒌝\|𒆠𒆠?\|𒇽𒄿𒌝\|𒇽𒇽𒀸\|𒇽𒇽𒌝\|𒇽𒌝𒁀\|𒈠𒈠?\|𒈠𒋻?\|𒈠𒋻𒁹\|𒈠𒌝𒁀\|𒈷𒀀?\|𒈷𒀸?\|𒈷𒁹?\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/
syn match curryAkkBuiltin /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(𒈷𒁹𒀸\|𒈷𒌝?\|𒉡𒀭?\|𒉡𒃲𒁹\|𒉡𒃲𒌑\|𒉡𒅆?\|𒉡𒅆𒌝\|𒉡𒆠?\|𒉡𒆠𒋻\|𒉡𒉡𒁹\|𒉡𒉡𒈷\|𒉡𒌝?\|𒊕𒊕?\|𒊕𒊕𒁹\|𒊕𒊕𒄿\|𒊕𒊕𒊕\|𒊕𒊕𒌝\|𒋻𒈷𒈷\|𒌑𒌝𒁀\|𒌝𒀸?\|𒌝𒁀𒁹\|𒌝𒁀𒄿\|𒌝𒁀𒊕\|𒌝𒁀𒋻\|𒌝𒁹𒁹\|𒌝𒂗𒁹\|𒌝𒃲?\|𒌝𒈠?\|𒌝𒈠𒁹\|𒌝𒉡?\|𒌝𒊕𒊕\|𒌝𒌋𒁹\|𒌝𒌑𒋻\|lā\|𒀀𒀸\|𒀀𒌝\|𒀭𒀸\|𒀭𒄿\|𒀭𒆠\|𒀭𒇽\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/
syn match curryAkkBuiltin /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(𒀭𒈠\|𒀭𒈷\|𒀭𒌑\|𒀭𒌝\|𒀸𒀸\|𒀸𒁹\|𒀸𒄿\|𒀸𒇽\|𒀸𒊕\|𒀸𒋻\|𒀸𒌋\|𒁀𒁹\|𒁀𒈠\|𒁀𒈷\|𒁀𒋻\|𒁹?\|𒂍?\|𒂍𒁀\|𒂍𒂗\|𒂍𒅆\|𒂍𒇲\|𒂍𒈷\|𒂍𒉡\|𒃲𒀀\|𒃲𒁹\|𒃲𒃲\|𒃲𒌑\|𒄀𒁹\|𒄀𒌋\|𒄭𒁹\|𒄭𒈠\|𒄭𒉡\|𒄭𒊕\|𒄭𒍪\|𒄷𒁹\|𒄷𒌝\|𒄿𒃲\|𒄿𒌝\|𒅁𒁹\|𒅁𒈷\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/
syn match curryAkkBuiltin /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(𒅆𒀸\|𒅆𒁀\|𒅆𒁹\|𒅆𒄿\|𒅆𒋻\|𒅆𒌋\|𒅆𒌝\|𒆠?\|𒆠𒀸\|𒆠𒋻\|𒇲𒆠\|𒇲𒇲\|𒇲𒌋\|𒇲𒌑\|𒇽?\|𒇽𒀸\|𒇽𒄿\|𒇽𒌝\|𒈠𒀸\|𒈠𒂗\|𒈠𒈾\|𒈠𒋻\|𒈠𒌝\|𒈧𒀸\|𒈧𒁹\|𒈷?\|𒈷𒁀\|𒈷𒁹\|𒈷𒅆\|𒈷𒈷\|𒈷𒌝\|𒉡𒁹\|𒉡𒃲\|𒉡𒄿\|𒉡𒅆\|𒉡𒉡\|𒉡𒊕\|𒊕𒈷\|𒊕𒋻\|𒊕𒌝\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/
syn match curryAkkBuiltin /\%(^\|[[:space:]()\[\]'`\",;]\)\@<=\%(𒋻𒀀\|𒋻𒁹\|𒋻𒂍\|𒋻𒇲\|𒌋𒊕\|𒌑𒁹\|𒌑𒄿\|𒌑𒅁\|𒌑𒊕\|𒌑𒌑\|𒌑𒌝\|𒌝?\|𒌝𒀸\|𒌝𒁀\|𒌝𒁹\|𒌝𒂗\|𒌝𒃲\|𒌝𒄿\|𒌝𒅁\|𒌝𒅆\|𒌝𒆜\|𒌝𒆠\|𒌝𒇽\|𒌝𒈠\|𒌝𒈷\|𒌝𒊕\|𒌝𒋻\|𒌝𒌝\|𒃲\|𒅆\|𒆜\|𒆠\|𒇲\|𒈧\|𒉡\|𒊕\|𒋻\|𒍪\)\%([[:space:]()\[\]'`\",;]\|$\)\@=/

" Multi-group spaced numeral — outranks synonyms (defined last)
syn match   curryCuneiformNumber /\%(^\|[[:space:]()\[\]\x27`",;]\)\@<=[𒁹𒌋𒑊]\+\%( [𒁹𒌋𒑊]\+\)\+\%([[:space:]()\[\]\x27`",;]\|$\)\@=/

syn sync fromstart

hi def link curryComment          Comment
hi def link curryBlockComment     Comment
hi def link curryDatumComment     Comment
hi def link curryString           String
hi def link curryStringEscape     SpecialChar
hi def link curryChar             Character
hi def link curryBoolean          Boolean
hi def link curryKeywordObj       Special
hi def link curryQuote            Special
hi def link curryNumber           Number
hi def link curryRadixNumber      Number
hi def link currySexagesimal      Number
hi def link curryCuneiformNumber  Number
hi def link curryForm             Statement
hi def link curryAkkForm          Statement
hi def link curryBuiltin          Function
hi def link curryAkkBuiltin       Function

let b:current_syntax = "curry"
