# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BUILD_SOURCE_DIRS "/Volumes/Antennae/src/curry.old;/Volumes/Antennae/src/curry.old/build_hb")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libgc1t64 | libgc1 | libgc2, libgmp10")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_RECOMMENDS "libsqlite3-0,      libssl3 | libssl1.1,      libcurl4 | libcurl4t64,      libgit2-1.1 | libgit2-1.5 | libgit2-1.7 | libgit2-1.9,      libpng16-16 | libpng16-16t64,      libjpeg-turbo8 | libjpeg62-turbo | libjpeg-turbo9,      libpaho-mqtt3cs1 | libpaho-mqtt3c1,      libldap-2.5-0 | libldap-2.4-2")
set(CPACK_DEBIAN_PACKAGE_SECTION "interpreters")
set(CPACK_DEBIAN_PACKAGE_SUGGESTS "libqt6widgets6, libqt6opengl6,      libplplot19 | libplplot17,      libreadline8 | libreadline9")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/opt/homebrew/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "curry built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/Volumes/Antennae/src/curry.old;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "curry-scheme 0.7.3")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "curry-scheme 0.7.3")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/Volumes/Antennae/src/curry.old/build_hb/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "metanoia@gmail.com")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "R7RS Scheme interpreter featuring Boehm GC, GMP arbitrary-precision arithmetic, actor-model concurrency (pthreads), Clifford algebra multivectors, symbolic CAS, and a rich optional module system (JSON, SQLite, Redis, S3/Azure/GCS, GraphQL, Git, image I/O, Qt6, PLplot).")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/opt/homebrew/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Curry Scheme — R7RS interpreter with actor concurrency and extended numerics")
set(CPACK_PACKAGE_FILE_NAME "curry-scheme-0.7.3-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "curry-scheme 0.7.3")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "curry-scheme 0.7.3")
set(CPACK_PACKAGE_NAME "curry-scheme")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Chris Ó Luanaigh")
set(CPACK_PACKAGE_VERSION "0.7.3")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "7")
set(CPACK_PACKAGE_VERSION_PATCH "3")
set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")
set(CPACK_RESOURCE_FILE_LICENSE "/Volumes/Antennae/src/curry.old/LICENSE")
set(CPACK_RESOURCE_FILE_README "/Volumes/Antennae/src/curry.old/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/opt/homebrew/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/Volumes/Antennae/src/curry.old;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Volumes/Antennae/src/curry.old/build_hb/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "curry-scheme-0.7.3-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Darwin-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Darwin")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Darwin-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Volumes/Antennae/src/curry.old/build_hb/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
