;;; (curry lang) — Language pack install / load / generate utilities.
;;;
;;; Provides a download-and-cache workflow on top of the built-in
;;; register-language! / set-active-language! primitives.
;;;
;;; Quick start:
;;;   (import (curry lang))
;;;   (lang:install! "warlpiri")   ; fetch from registry + cache locally
;;;   (lang:load!    "warlpiri")   ; load from cache (offline-safe)

(define-library (curry lang)
  (import (scheme base)
          (scheme file)
          (scheme read)
          (scheme write)
          (curry network))   ; for http-get

  (export
    lang:registry-url
    lang:cache-dir
    lang:list-available
    lang:fetch
    lang:install!
    lang:load!
    lang:load-file!
    lang:generate)

  (begin

    ;;; Registry base URL — override with CURRY_LANG_REGISTRY_URL env var.
    (define lang:registry-url
      (let ((env (get-environment-variable "CURRY_LANG_REGISTRY_URL")))
        (if (and env (not (string=? env "")))
            env
            "https://raw.githubusercontent.com/your-org/curry/main/langs")))

    ;;; Local cache directory (~/.curry/langs/).
    (define lang:cache-dir
      (let ((home (or (get-environment-variable "HOME") ".")))
        (string-append home "/.curry/langs")))

    (define (ensure-cache-dir!)
      ;; POSIX mkdir via shell — only needed for lang:install!
      (when (not (file-exists? lang:cache-dir))
        (system (string-append "mkdir -p '" lang:cache-dir "'"))))

    (define (cache-path id)
      (string-append lang:cache-dir "/" id ".scm"))

    ;;; Fetch the registry index (index.scm) and return the lang-index list.
    (define (lang:list-available)
      (let* ((url (string-append lang:registry-url "/index.scm"))
             (src (http-get url)))
        (eval (read (open-input-string src)))))

    ;;; Fetch the raw .scm source for language ID from the registry.
    ;;; Returns a string, or raises on network error.
    (define (lang:fetch id)
      (let ((url (string-append lang:registry-url "/" id ".scm")))
        (http-get url)))

    ;;; Fetch and save to cache; does not load into the runtime.
    (define (lang:install! id)
      (ensure-cache-dir!)
      (let ((src  (lang:fetch id))
            (path (cache-path id)))
        (call-with-port (open-output-file path)
          (lambda (p) (write-string src p)))
        path))

    ;;; Load from cache (no network access).
    (define (lang:load! id)
      (let ((path (cache-path id)))
        (if (file-exists? path)
            (lang:load-file! path)
            (error "lang:load!: pack not installed" id
                   "(run (lang:install! id) first)"))))

    ;;; Load from any local .scm file path.
    (define (lang:load-file! path)
      (let ((p (open-input-file path))
            (env (interaction-environment)))
        (dynamic-wind
          (lambda () #f)
          (lambda ()
            (let loop ()
              (let ((form (read p)))
                (unless (eof-object? form)
                  (eval form env)
                  (loop)))))
          (lambda () (close-input-port p)))))

    ;;; Generate .scm source from an alist spec (same format as register-language!).
    ;;; Returns the source as a string, suitable for writing to a file.
    (define (lang:generate spec)
      (let* ((id      (cdr (assq 'id spec)))
             (dname   (let ((p (assq 'display-name spec)))
                        (if p (cdr p) id)))
             (intro   (let ((p (assq 'intro spec)))
                        (if p (cdr p) "")))
             (epre    (let ((p (assq 'error-preamble spec)))
                        (if p (cdr p) "")))
             (mps     (let ((p (assq 'mappings spec)))
                        (if p (cdr p) '())))
             (out     (open-output-string)))
        (write-string
          (string-append
            ";;; " id ".scm — " dname " language pack for Curry Scheme.\n"
            ";;; Generated by (curry lang) lang:generate\n\n"
            "(import (curry lang))\n\n"
            "(register-language!\n"
            "  `((id           . \"" id "\")\n"
            "    (display-name . \"" dname "\")\n"
            "    (intro        . \"" intro "\")\n"
            "    (error-preamble . \"" epre "\")\n"
            "    (mappings     .\n")
          out)
        (for-each
          (lambda (m)
            (let ((foreign (car m))
                  (canon   (cadr m))
                  (desc    (if (null? (cddr m)) #f (caddr m))))
              (write-string
                (if desc
                    (string-append "      (" (symbol->string foreign) " "
                                   (symbol->string canon) " \""
                                   desc "\")\n")
                    (string-append "      (" (symbol->string foreign) " "
                                   (symbol->string canon) ")\n"))
                out)))
          mps)
        (write-string "      )))\n" out)
        (get-output-string out)))

    ))
